twig:
    cache:                      '%kernel.cache_dir%/twig'
#    cache:                      false
    # The default format options used by the date filter
    date:
        format:                 'Y-m-d, H:i:s'
        interval_format:        '%d days'
        # The timezone used when formatting dates, when set to null, the timezone returned by date_default_timezone_get() is used
        timezone:               Europe/Paris
    default_path:               '%kernel.project_dir%/templates'
    file_name_pattern:          '*.twig'
    form_themes:
        # Default:
        - bootstrap_5_layout.html.twig
    # The default format options for the number_format filter
    number_format:
        decimals:               0
        decimal_point:          ','
        thousands_separator:    ' '
    paths:
        '%kernel.project_dir%/templates': 'App'
    globals:
        metas:   '%metas%'
        classes: '%classes%'
        images:  '%images%'
        games:   '%games%'

when@test:
    twig:
        strict_variables: true
        cache:            '%kernel.cache_dir%/twig-test'
