<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241231013644 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'App';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_garage (id INT UNSIGNED AUTO_INCREMENT NOT NULL, setting_blueprint_id INT UNSIGNED DEFAULT NULL, setting_brand_id INT UNSIGNED DEFAULT NULL, setting_class_id INT UNSIGNED DEFAULT NULL, setting_level_id INT UNSIGNED DEFAULT NULL, setting_unit_price_id INT UNSIGNED DEFAULT NULL, stars SMALLINT UNSIGNED DEFAULT 3 NOT NULL, game_update SMALLINT UNSIGNED DEFAULT 0 NOT NULL, car_order SMALLINT UNSIGNED DEFAULT 99 NOT NULL, stat_order SMALLINT UNSIGNED DEFAULT 99 NOT NULL, level SMALLINT UNSIGNED DEFAULT 0 NOT NULL, epic SMALLINT UNSIGNED DEFAULT 0 NOT NULL, model VARCHAR(128) NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7A250C8B989D9B62 (slug), INDEX IDX_7A250C8B5869B9F3 (setting_blueprint_id), INDEX IDX_7A250C8BEA7CE8F2 (setting_brand_id), INDEX IDX_7A250C8B448933EA (setting_class_id), INDEX IDX_7A250C8BF138735D (setting_level_id), INDEX IDX_7A250C8B4A5104AF (setting_unit_price_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_inventory (id INT UNSIGNED AUTO_INCREMENT NOT NULL, category VARCHAR(16) NOT NULL, label VARCHAR(32) NOT NULL, value INT UNSIGNED DEFAULT 0 NOT NULL, filter VARCHAR(32) DEFAULT \'---\' NOT NULL, position SMALLINT DEFAULT NULL, active TINYINT(1) NOT NULL, slug VARCHAR(128) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_19421503989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_mission (id INT UNSIGNED AUTO_INCREMENT NOT NULL, task_id INT UNSIGNED NOT NULL, type_id INT UNSIGNED NOT NULL, week SMALLINT UNSIGNED DEFAULT 1 NOT NULL, region VARCHAR(64) DEFAULT NULL, track VARCHAR(64) DEFAULT NULL, class VARCHAR(16) DEFAULT NULL, brand VARCHAR(64) DEFAULT NULL, description VARCHAR(32) DEFAULT NULL, success SMALLINT UNSIGNED DEFAULT 0 NOT NULL, target SMALLINT UNSIGNED DEFAULT 1 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_7D3A72718DB60186 (task_id), INDEX IDX_7D3A7271C54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE app_race (id INT UNSIGNED AUTO_INCREMENT NOT NULL, mode_id INT UNSIGNED NOT NULL, season_id INT UNSIGNED NOT NULL, time_id INT UNSIGNED NOT NULL, track_id INT UNSIGNED NOT NULL, race_order SMALLINT UNSIGNED DEFAULT 0, finished TINYINT(1) DEFAULT 0 NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_DF419E0F989D9B62 (slug), INDEX IDX_DF419E0F77E5854A (mode_id), INDEX IDX_DF419E0F4EC001D1 (season_id), INDEX IDX_DF419E0F5EEADD3B (time_id), INDEX IDX_DF419E0F5ED23C43 (track_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE garage_blueprint (id INT UNSIGNED AUTO_INCREMENT NOT NULL, garage_id INT UNSIGNED DEFAULT NULL, star1 VARCHAR(8) DEFAULT NULL, star2 SMALLINT UNSIGNED DEFAULT NULL, star3 SMALLINT UNSIGNED DEFAULT NULL, star4 SMALLINT UNSIGNED DEFAULT NULL, star5 SMALLINT UNSIGNED DEFAULT NULL, star6 SMALLINT UNSIGNED DEFAULT NULL, total SMALLINT UNSIGNED DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_FEB8406FC4FFF555 (garage_id), INDEX name_idx (id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE garage_boolean (id INT UNSIGNED AUTO_INCREMENT NOT NULL, garage_id INT UNSIGNED DEFAULT NULL, locked TINYINT(1) DEFAULT 1 NOT NULL, full_blueprint TINYINT(1) DEFAULT 0 NOT NULL, gold TINYINT(1) DEFAULT 0 NOT NULL, to_unlock TINYINT(1) DEFAULT 0 NOT NULL, to_upgrade TINYINT(1) DEFAULT 0 NOT NULL, to_gold TINYINT(1) DEFAULT 0 NOT NULL, install_speed TINYINT(1) DEFAULT 0 NOT NULL, full_speed TINYINT(1) DEFAULT 0 NOT NULL, install_acceleration TINYINT(1) DEFAULT 0 NOT NULL, full_acceleration TINYINT(1) DEFAULT 0 NOT NULL, install_handly TINYINT(1) DEFAULT 0 NOT NULL, full_handly TINYINT(1) DEFAULT 0 NOT NULL, install_nitro TINYINT(1) DEFAULT 0 NOT NULL, full_nitro TINYINT(1) DEFAULT 0 NOT NULL, install_common TINYINT(1) DEFAULT 0 NOT NULL, full_common TINYINT(1) DEFAULT 0 NOT NULL, install_rare TINYINT(1) DEFAULT 0 NOT NULL, full_rare TINYINT(1) DEFAULT 0 NOT NULL, install_epic TINYINT(1) DEFAULT 0 NOT NULL, full_epic TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_CC564F8C4FFF555 (garage_id), INDEX name_idx (id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE garage_rank (id INT UNSIGNED AUTO_INCREMENT NOT NULL, garage_id INT UNSIGNED DEFAULT NULL, star0 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star1 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star2 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star3 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star4 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star5 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star6 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_EB0F950EC4FFF555 (garage_id), INDEX name_idx (id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE garage_stat_max (id INT UNSIGNED AUTO_INCREMENT NOT NULL, garage_id INT UNSIGNED DEFAULT NULL, speed DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, acceleration DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, handly DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, nitro DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, average DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_91F01015C4FFF555 (garage_id), INDEX name_idx (id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE garage_stat_min (id INT UNSIGNED AUTO_INCREMENT NOT NULL, garage_id INT UNSIGNED DEFAULT NULL, speed DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, acceleration DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, handly DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, nitro DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, average DOUBLE PRECISION UNSIGNED DEFAULT \'0\' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ADFD2F4CC4FFF555 (garage_id), INDEX name_idx (id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE garage_upgrade (id INT UNSIGNED AUTO_INCREMENT NOT NULL, garage_id INT UNSIGNED DEFAULT NULL, speed SMALLINT UNSIGNED DEFAULT 0 NOT NULL, acceleration SMALLINT UNSIGNED DEFAULT 0 NOT NULL, handly SMALLINT UNSIGNED DEFAULT 0 NOT NULL, nitro SMALLINT UNSIGNED DEFAULT 0 NOT NULL, common SMALLINT UNSIGNED DEFAULT 0 NOT NULL, rare SMALLINT UNSIGNED DEFAULT 0 NOT NULL, epic SMALLINT UNSIGNED DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_3126988AC4FFF555 (garage_id), INDEX name_idx (id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mission_task (id INT UNSIGNED AUTO_INCREMENT NOT NULL, value VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7B3C772A1D775834 (value), UNIQUE INDEX UNIQ_7B3C772A989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE mission_type (id INT UNSIGNED AUTO_INCREMENT NOT NULL, value VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_A59CFB261D775834 (value), UNIQUE INDEX UNIQ_A59CFB26989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race_mode (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(32) NOT NULL, slug VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_CAB757E45E237E06 (name), UNIQUE INDEX UNIQ_CAB757E4989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race_region (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_6534EFA55E237E06 (name), UNIQUE INDEX UNIQ_6534EFA5989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race_season (id INT UNSIGNED AUTO_INCREMENT NOT NULL, chapter SMALLINT UNSIGNED DEFAULT 1 NOT NULL, name VARCHAR(64) NOT NULL, slug VARCHAR(128) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_9AB2457A5E237E06 (name), UNIQUE INDEX UNIQ_9AB2457A989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race_time (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name SMALLINT UNSIGNED NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_32E9880A5E237E06 (name), INDEX name_idx (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE race_track (id INT UNSIGNED AUTO_INCREMENT NOT NULL, region_id INT UNSIGNED DEFAULT NULL, name_english VARCHAR(64) NOT NULL, name_french VARCHAR(64) DEFAULT NULL, slug VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_30DDD9B724E847BE (name_english), UNIQUE INDEX UNIQ_30DDD9B7989D9B62 (slug), INDEX IDX_30DDD9B798260155 (region_id), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting_blueprint (id INT UNSIGNED AUTO_INCREMENT NOT NULL, star1 VARCHAR(3) NOT NULL, star2 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star3 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star4 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star5 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, star6 SMALLINT UNSIGNED DEFAULT 0 NOT NULL, total SMALLINT UNSIGNED DEFAULT 0 NOT NULL, slug VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7B83705C989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting_brand (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, cars_number SMALLINT UNSIGNED DEFAULT 0 NOT NULL, slug VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_55FA0A395E237E06 (name), UNIQUE INDEX UNIQ_55FA0A39989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting_class (id INT UNSIGNED AUTO_INCREMENT NOT NULL, label VARCHAR(8) NOT NULL, value VARCHAR(8) NOT NULL, class_order SMALLINT UNSIGNED DEFAULT 1 NOT NULL, cars_number SMALLINT UNSIGNED DEFAULT 0 NOT NULL, median SMALLINT UNSIGNED DEFAULT 0 NOT NULL, slug VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_A4E3EAFE989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting_level (id INT UNSIGNED AUTO_INCREMENT NOT NULL, level SMALLINT UNSIGNED DEFAULT 10 NOT NULL, common SMALLINT UNSIGNED DEFAULT 0 NOT NULL, rare SMALLINT UNSIGNED DEFAULT 0 NOT NULL, epic SMALLINT UNSIGNED DEFAULT 0 NOT NULL, slug VARCHAR(128) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_D3423F72989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE setting_unit_price (id INT UNSIGNED AUTO_INCREMENT NOT NULL, level01 INT UNSIGNED DEFAULT 0 NOT NULL, level02 INT UNSIGNED DEFAULT 0 NOT NULL, level03 INT UNSIGNED DEFAULT 0 NOT NULL, level04 INT UNSIGNED DEFAULT 0 NOT NULL, level05 INT UNSIGNED DEFAULT 0 NOT NULL, level06 INT UNSIGNED DEFAULT 0 NOT NULL, level07 INT UNSIGNED DEFAULT 0 NOT NULL, level08 INT UNSIGNED DEFAULT 0 NOT NULL, level09 INT UNSIGNED DEFAULT 0 NOT NULL, level10 INT UNSIGNED DEFAULT 0 NOT NULL, level11 INT UNSIGNED DEFAULT 0, level12 INT UNSIGNED DEFAULT 0, level13 INT UNSIGNED DEFAULT 0, common INT UNSIGNED DEFAULT 0 NOT NULL, rare INT UNSIGNED DEFAULT 0 NOT NULL, epic INT UNSIGNED DEFAULT 0, slug VARCHAR(128) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_87AB43F2989D9B62 (slug), INDEX slug_idx (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE app_garage ADD CONSTRAINT FK_7A250C8B5869B9F3 FOREIGN KEY (setting_blueprint_id) REFERENCES setting_blueprint (id)');
        $this->addSql('ALTER TABLE app_garage ADD CONSTRAINT FK_7A250C8BEA7CE8F2 FOREIGN KEY (setting_brand_id) REFERENCES setting_brand (id)');
        $this->addSql('ALTER TABLE app_garage ADD CONSTRAINT FK_7A250C8B448933EA FOREIGN KEY (setting_class_id) REFERENCES setting_class (id)');
        $this->addSql('ALTER TABLE app_garage ADD CONSTRAINT FK_7A250C8BF138735D FOREIGN KEY (setting_level_id) REFERENCES setting_level (id)');
        $this->addSql('ALTER TABLE app_garage ADD CONSTRAINT FK_7A250C8B4A5104AF FOREIGN KEY (setting_unit_price_id) REFERENCES setting_unit_price (id)');
        $this->addSql('ALTER TABLE app_mission ADD CONSTRAINT FK_7D3A72718DB60186 FOREIGN KEY (task_id) REFERENCES mission_task (id)');
        $this->addSql('ALTER TABLE app_mission ADD CONSTRAINT FK_7D3A7271C54C8C93 FOREIGN KEY (type_id) REFERENCES mission_type (id)');
        $this->addSql('ALTER TABLE app_race ADD CONSTRAINT FK_DF419E0F77E5854A FOREIGN KEY (mode_id) REFERENCES race_mode (id)');
        $this->addSql('ALTER TABLE app_race ADD CONSTRAINT FK_DF419E0F4EC001D1 FOREIGN KEY (season_id) REFERENCES race_season (id)');
        $this->addSql('ALTER TABLE app_race ADD CONSTRAINT FK_DF419E0F5EEADD3B FOREIGN KEY (time_id) REFERENCES race_time (id)');
        $this->addSql('ALTER TABLE app_race ADD CONSTRAINT FK_DF419E0F5ED23C43 FOREIGN KEY (track_id) REFERENCES race_track (id)');
        $this->addSql('ALTER TABLE garage_blueprint ADD CONSTRAINT FK_FEB8406FC4FFF555 FOREIGN KEY (garage_id) REFERENCES app_garage (id)');
        $this->addSql('ALTER TABLE garage_boolean ADD CONSTRAINT FK_CC564F8C4FFF555 FOREIGN KEY (garage_id) REFERENCES app_garage (id)');
        $this->addSql('ALTER TABLE garage_rank ADD CONSTRAINT FK_EB0F950EC4FFF555 FOREIGN KEY (garage_id) REFERENCES app_garage (id)');
        $this->addSql('ALTER TABLE garage_stat_max ADD CONSTRAINT FK_91F01015C4FFF555 FOREIGN KEY (garage_id) REFERENCES app_garage (id)');
        $this->addSql('ALTER TABLE garage_stat_min ADD CONSTRAINT FK_ADFD2F4CC4FFF555 FOREIGN KEY (garage_id) REFERENCES app_garage (id)');
        $this->addSql('ALTER TABLE garage_upgrade ADD CONSTRAINT FK_3126988AC4FFF555 FOREIGN KEY (garage_id) REFERENCES app_garage (id)');
        $this->addSql('ALTER TABLE race_track ADD CONSTRAINT FK_30DDD9B798260155 FOREIGN KEY (region_id) REFERENCES race_region (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE app_garage DROP FOREIGN KEY FK_7A250C8B5869B9F3');
        $this->addSql('ALTER TABLE app_garage DROP FOREIGN KEY FK_7A250C8BEA7CE8F2');
        $this->addSql('ALTER TABLE app_garage DROP FOREIGN KEY FK_7A250C8B448933EA');
        $this->addSql('ALTER TABLE app_garage DROP FOREIGN KEY FK_7A250C8BF138735D');
        $this->addSql('ALTER TABLE app_garage DROP FOREIGN KEY FK_7A250C8B4A5104AF');
        $this->addSql('ALTER TABLE app_mission DROP FOREIGN KEY FK_7D3A72718DB60186');
        $this->addSql('ALTER TABLE app_mission DROP FOREIGN KEY FK_7D3A7271C54C8C93');
        $this->addSql('ALTER TABLE app_race DROP FOREIGN KEY FK_DF419E0F77E5854A');
        $this->addSql('ALTER TABLE app_race DROP FOREIGN KEY FK_DF419E0F4EC001D1');
        $this->addSql('ALTER TABLE app_race DROP FOREIGN KEY FK_DF419E0F5EEADD3B');
        $this->addSql('ALTER TABLE app_race DROP FOREIGN KEY FK_DF419E0F5ED23C43');
        $this->addSql('ALTER TABLE garage_blueprint DROP FOREIGN KEY FK_FEB8406FC4FFF555');
        $this->addSql('ALTER TABLE garage_boolean DROP FOREIGN KEY FK_CC564F8C4FFF555');
        $this->addSql('ALTER TABLE garage_rank DROP FOREIGN KEY FK_EB0F950EC4FFF555');
        $this->addSql('ALTER TABLE garage_stat_max DROP FOREIGN KEY FK_91F01015C4FFF555');
        $this->addSql('ALTER TABLE garage_stat_min DROP FOREIGN KEY FK_ADFD2F4CC4FFF555');
        $this->addSql('ALTER TABLE garage_upgrade DROP FOREIGN KEY FK_3126988AC4FFF555');
        $this->addSql('ALTER TABLE race_track DROP FOREIGN KEY FK_30DDD9B798260155');
        $this->addSql('DROP TABLE app_garage');
        $this->addSql('DROP TABLE app_inventory');
        $this->addSql('DROP TABLE app_mission');
        $this->addSql('DROP TABLE app_race');
        $this->addSql('DROP TABLE garage_blueprint');
        $this->addSql('DROP TABLE garage_boolean');
        $this->addSql('DROP TABLE garage_rank');
        $this->addSql('DROP TABLE garage_stat_max');
        $this->addSql('DROP TABLE garage_stat_min');
        $this->addSql('DROP TABLE garage_upgrade');
        $this->addSql('DROP TABLE mission_task');
        $this->addSql('DROP TABLE mission_type');
        $this->addSql('DROP TABLE race_mode');
        $this->addSql('DROP TABLE race_region');
        $this->addSql('DROP TABLE race_season');
        $this->addSql('DROP TABLE race_time');
        $this->addSql('DROP TABLE race_track');
        $this->addSql('DROP TABLE setting_blueprint');
        $this->addSql('DROP TABLE setting_brand');
        $this->addSql('DROP TABLE setting_class');
        $this->addSql('DROP TABLE setting_level');
        $this->addSql('DROP TABLE setting_unit_price');
    }
}
