parameters:
    ### METAS
    metas:
        title:              'Asphalt Legends Unite'
        author:             'Giancarlo PALUMBO'
        email:              'giancarlo.palumbo@free.fr'
        description:        ~
        generator:          ~
    ### CLASSES
    classes:
        table:
            empty:          'bg-danger-subtle text-center text-uppercase text-danger fw-bolder p-3'
        button:
            table:          'btn btn-sm rounded-3 py-1 m-0'
            back:           'btn btn-outline-warning text-uppercase btn-lg fw-bolder rounded-start-5 w-25'
            success:        'btn btn-outline-success text-uppercase btn-lg fw-bolder rounded-end-5 w-75'
            delete:         'btn btn-outline-danger text-uppercase'
    ### GAMES
    games:
        pack_blueprint:     6
        pack_price:         900
        evo_target:         24
    ### ICONS
    icons:
        speed:              ⚡
        acceleration:       🚀
        handling:           🎯
        nitro:              🔥
        check:              'fa-solid fa-check'
        xmark:              'fa-solid fa-xmark'
        rocket:             'fa-solid fa-rocket'        # Speed
        gauge:              'fa-solid fa-gauge-high'    # Acceleration
        gear:               'fa-solid fa-gear'          # Handling
        fire:               'fa-solid fa-fire'          # Nitro
        star:
            full:           'fa-solid fa-star'
            empty:          'fa-regular fa-star'
            half:           'fa-solid fa-star-half-stroke'
        class:
            d:              'fa-solid fa-d'
            c:              'fa-solid fa-c'
            b:              'fa-solid fa-b'
            a:              'fa-solid fa-a'
            s:              'fa-solid fa-s'
    ### FOLDERS
    folders.cache:          '%kernel.project_dir%/public/cache/'
when@dev:
    parameters:
        ### CACHES
        cache_lifetime:
            dashboards:     60   # 1 min
            sitemaps:       3    # 5 mins
            statistics:     300  # 5 mins
        ### IMAGES
        images:
            avatar:         'images/sako-01.jpg'
            logo:
                front:      'images/logo-yellow.png'
                back:       'images/logo-green.png'
when@prod:
    parameters:
        ### CACHES
        cache_lifetime:
            dashboards:     3600    # (60 * 60 = 1 hour)
            sitemaps:       2678400 # (60 * 60 * 24 * 31 = 1 month)
            statistics:     2678400 # (60 * 60 * 24 * 31 = 1 month)
        ### IMAGES
        images:
            avatar:         'images/sako-01.jpg'
            logo:
                front:      'images/logo-white.png'
                back:       'images/logo-blue.png'
