id: 182
stars: 6
gameUpdate: 27
carOrder: 36
statOrder: 25
level: 0
epic: 1
model: Drakuma
slug: ajlani-drakuma
blueprint:
    star1: '42'
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 42
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3532
    star1: 3683
    star2: 3863
    star3: 4054
    star4: 4251
    star5: 4483
    star6: 4702
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 441.0
    acceleration: 81.56
    handling: 47.91
    nitro: 60.58
    average: 157.76
statMin:
    speed: 419.0
    acceleration: 77.5
    handling: 38.68
    nitro: 46.25
    average: 145.36
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Ajlani
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
