id: 112
stars: 5
gameUpdate: 16
carOrder: 39
statOrder: 27
level: 12
epic: 8
model: IE
slug: apollo-ie
blueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 2
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2430
    star1: 2638
    star2: 2939
    star3: 3205
    star4: 3586
    star5: 3953
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 348.3
    acceleration: 84.65
    handling: 73.17
    nitro: 69.12
    average: 143.81
statMin:
    speed: 335.0
    acceleration: 75.7
    handling: 47.64
    nitro: 51.09
    average: 127.36
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 32
    rare: 20
    epic: 8
settingBlueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
settingBrand:
    name: Apollo
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
