id: 149
stars: 4
gameUpdate: 22
carOrder: 11
statOrder: 66
level: 11
epic: 5
model: AF10
slug: arash-af10
blueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 1905
    star1: 2128
    star2: 2473
    star3: 2814
    star4: 3112
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 337.0
    acceleration: 78.73
    handling: 50.41
    nitro: 59.6
    average: 131.44
statMin:
    speed: 323.0
    acceleration: 73.9
    handling: 39.2
    nitro: 44.1
    average: 120.05
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 24
    rare: 16
    epic: 4
settingBlueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
settingBrand:
    name: Arash
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 5750
    level02: 9400
    level03: 15000
    level04: 22500
    level05: 32500
    level06: 45500
    level07: 63500
    level08: 89000
    level09: 125000
    level10: 175000
    level11: 245000
    level12: null
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
