id: 292
stars: 6
gameUpdate: 44
carOrder: 73
statOrder: 4
level: 3
epic: 0
model: Imperium
slug: arash-imperium
blueprint:
    star1: ''
    star2: 3
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 3
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 1
    handling: 3
    nitro: 9
    mark: 3
    division: 9
rank:
    star0: 4122
    star1: 4280
    star2: 4464
    star3: 4660
    star4: 4862
    star5: 5097
    star6: 5315
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 535.3
    acceleration: 89.83
    handling: 55.36
    nitro: 33.57
    average: 178.52
statMin:
    speed: 520.0
    acceleration: 87.4
    handling: 43.71
    nitro: 12.78
    average: 165.97
upgrade:
    speed: 3
    acceleration: 3
    handling: 3
    nitro: 3
    common: 8
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 45
    star3: 50
    star4: 55
    star5: 70
    star6: 80
    total: 300
settingBrand:
    name: Arash
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
