id: 135
stars: 4
gameUpdate: 20
carOrder: 10
statOrder: 28
level: 11
epic: 4
model: 'V12 Speedster'
slug: aston-martin-v12-speedster
blueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 1
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 1496
    star1: 1759
    star2: 2106
    star3: 2450
    star4: 2735
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 303.9
    acceleration: 77.32
    handling: 86.2
    nitro: 68.94
    average: 134.09
statMin:
    speed: 300.0
    acceleration: 68.5
    handling: 37.23
    nitro: 42.72
    average: 112.11
upgrade:
    speed: 9
    acceleration: 9
    handling: 9
    nitro: 9
    common: 24
    rare: 12
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
settingBrand:
    name: 'Aston Martin'
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 12
    epic: 4
settingUnitPrice:
    level01: 5060
    level02: 8300
    level03: 13200
    level04: 19800
    level05: 28600
    level06: 40000
    level07: 56000
    level08: 78500
    level09: 110000
    level10: 154000
    level11: 215000
    level12: null
    level13: null
    common: 30000
    rare: 60000
    epic: 180000
