id: 130
stars: 6
gameUpdate: 19
carOrder: 24
statOrder: 49
level: 8
epic: 8
model: Valkyrie
slug: aston-martin-valkyrie
blueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 8
    star5: 0
    star6: 0
    total: 147
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 2
    nitro: 1
    mark: 2
    division: 9
rank:
    star0: 3176
    star1: 3346
    star2: 3548
    star3: 3761
    star4: 3984
    star5: 4242
    star6: 4488
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 378.2
    acceleration: 80.3
    handling: 77.91
    nitro: 76.7
    average: 153.28
statMin:
    speed: 360.0
    acceleration: 73.0
    handling: 52.9
    nitro: 57.97
    average: 135.97
upgrade:
    speed: 8
    acceleration: 8
    handling: 8
    nitro: 8
    common: 16
    rare: 8
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: 'Aston Martin'
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
