id: 226
stars: 6
gameUpdate: 34
carOrder: 26
statOrder: 21
level: 3
epic: 1
model: 'DBS GT Zagato'
slug: aston-martin-dbs-gt-zagato
blueprint:
    star1: '70'
    star2: 14
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 84
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 2
    nitro: 1
    mark: 2
    division: 9
rank:
    star0: 2292
    star1: 2534
    star2: 2821
    star3: 3085
    star4: 3429
    star5: 3775
    star6: 4109
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 361.9
    acceleration: 80.65
    handling: 75.77
    nitro: 78.17
    average: 149.12
statMin:
    speed: 340.0
    acceleration: 69.4
    handling: 55.63
    nitro: 49.64
    average: 128.67
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: 'Aston Martin'
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
