id: 2
stars: 4
gameUpdate: 0
carOrder: 1
statOrder: 63
level: 11
epic: 8
model: Vulcan
slug: aston-martin-vulcan
blueprint:
    star1: '45'
    star2: 21
    star3: 28
    star4: 42
    star5: 0
    star6: 0
    total: 136
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 2
    mark: 4
    division: 9
rank:
    star0: 1970
    star1: 2202
    star2: 2452
    star3: 2736
    star4: 3012
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 343.5
    acceleration: 78.7
    handling: 47.8
    nitro: 64.79
    average: 133.7
statMin:
    speed: 328.0
    acceleration: 73.0
    handling: 36.63
    nitro: 50.33
    average: 121.99
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 20
    rare: 20
    epic: 8
settingBlueprint:
    star1: '45'
    star2: 21
    star3: 28
    star4: 42
    star5: 0
    star6: 0
    total: 136
settingBrand:
    name: 'Aston Martin'
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 11
    common: 20
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 3220
    level02: 5300
    level03: 8400
    level04: 12600
    level05: 18200
    level06: 25500
    level07: 35500
    level08: 50000
    level09: 70000
    level10: 98000
    level11: 137000
    level12: null
    level13: null
    common: 25000
    rare: 50000
    epic: 150000
