id: 159
stars: 5
gameUpdate: 23
carOrder: 43
statOrder: 35
level: 12
epic: 8
model: One77
slug: aston-martin-one77
blueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 2
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 2584
    star1: 2777
    star2: 3059
    star3: 3312
    star4: 3671
    star5: 4022
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 363.5
    acceleration: 79.34
    handling: 68.7
    nitro: 56.61
    average: 142.04
statMin:
    speed: 345.0
    acceleration: 71.2
    handling: 53.42
    nitro: 38.77
    average: 127.1
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 32
    rare: 20
    epic: 8
settingBlueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
settingBrand:
    name: 'Aston Martin'
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
