id: 131
stars: 6
gameUpdate: 19
carOrder: 36
statOrder: 22
level: 13
epic: 16
model: Victor
slug: aston-martin-victor
blueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 2950
    star1: 3118
    star2: 3323
    star3: 3512
    star4: 3761
    star5: 4010
    star6: 4255
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 371.4
    acceleration: 78.33
    handling: 76.84
    nitro: 69.63
    average: 149.05
statMin:
    speed: 360.0
    acceleration: 70.3
    handling: 54.85
    nitro: 47.57
    average: 133.18
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 20
    rare: 18
    epic: 2
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: 'Aston Martin'
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
