id: 124
stars: 4
gameUpdate: 18
carOrder: 27
statOrder: 47
level: 11
epic: 2
model: 'Corsa RRTurbo'
slug: ats-automobili-corsa-rrturbo
blueprint:
    star1: Key
    star2: 25
    star3: 38
    star4: 52
    star5: 0
    star6: 0
    total: 115
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 1979
    star1: 2279
    star2: 2675
    star3: 3060
    star4: 3392
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 321.7
    acceleration: 87.51
    handling: 51.19
    nitro: 52.48
    average: 128.22
statMin:
    speed: 305.0
    acceleration: 81.1
    handling: 39.39
    nitro: 17.31
    average: 110.7
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 24
    rare: 12
    epic: 2
settingBlueprint:
    star1: Key
    star2: 25
    star3: 38
    star4: 52
    star5: 0
    star6: 0
    total: 115
settingBrand:
    name: 'ATS Automobili'
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 12
    epic: 4
settingUnitPrice:
    level01: 5060
    level02: 8300
    level03: 13200
    level04: 19800
    level05: 28600
    level06: 40000
    level07: 56000
    level08: 78500
    level09: 110000
    level10: 154000
    level11: 215000
    level12: null
    level13: null
    common: 30000
    rare: 60000
    epic: 180000
