id: 258
stars: 6
gameUpdate: 39
carOrder: 28
statOrder: 57
level: 13
epic: 16
model: 'Battista Edizione Nino Farina'
slug: automobili-pininfarina-battista-edizione-nino-farina
blueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 1
    handling: 2
    nitro: 9
    mark: 3
    division: 9
rank:
    star0: 2845
    star1: 3012
    star2: 3213
    star3: 3397
    star4: 3643
    star5: 3889
    star6: 4125
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 362.6
    acceleration: 88.29
    handling: 61.0
    nitro: 42.38
    average: 138.57
statMin:
    speed: 350.0
    acceleration: 83.26
    handling: 45.33
    nitro: 26.22
    average: 126.2
upgrade:
    speed: 8
    acceleration: 9
    handling: 8
    nitro: 8
    common: 17
    rare: 8
    epic: 0
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: 'Automobili Pininfarina'
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
