id: 174
stars: 4
gameUpdate: 26
carOrder: 6
statOrder: 55
level: 9
epic: 1
model: 'Continental GT Speed'
slug: bentley-continental-gt-speed
blueprint:
    star1: '60'
    star2: 40
    star3: 51
    star4: 47
    star5: 0
    star6: 0
    total: 198
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 2
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 2229
    star1: 2483
    star2: 2749
    star3: 3052
    star4: 3342
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 348.3
    acceleration: 76.55
    handling: 74.23
    nitro: 59.35
    average: 139.61
statMin:
    speed: 335.0
    acceleration: 67.6
    handling: 58.75
    nitro: 45.17
    average: 126.63
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '60'
    star2: 40
    star3: 51
    star4: 63
    star5: 0
    star6: 0
    total: 214
settingBrand:
    name: Bentley
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 11
    common: 20
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 6440
    level02: 10500
    level03: 16800
    level04: 25200
    level05: 36400
    level06: 51000
    level07: 71500
    level08: 100000
    level09: 140000
    level10: 196000
    level11: 274000
    level12: null
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
