id: 103
stars: 4
gameUpdate: 14
carOrder: 32
statOrder: 12
level: 11
epic: 1
model: 'Continental GT3'
slug: bentley-continental-gt3
blueprint:
    star1: Key
    star2: 26
    star3: 38
    star4: 64
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 2
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 1139
    star1: 1500
    star2: 1920
    star3: 2353
    star4: 2783
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 300.8
    acceleration: 74.74
    handling: 72.52
    nitro: 50.79
    average: 124.71
statMin:
    speed: 285.0
    acceleration: 65.8
    handling: 45.88
    nitro: 20.94
    average: 104.41
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 28
    rare: 8
    epic: 1
settingBlueprint:
    star1: Key
    star2: 26
    star3: 38
    star4: 64
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Bentley
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
