id: 6
stars: 3
gameUpdate: 0
carOrder: 2
statOrder: 54
level: 10
epic: 4
model: '3.0 CSL Hommage'
slug: bmw-3-0-csl-hommage
blueprint:
    star1: '20'
    star2: 20
    star3: 50
    star4: 0
    star5: 0
    star6: 0
    total: 90
evo:
    number: 24
gauntlet:
    speed: 9
    acceleration: 9
    handling: 3
    nitro: 3
    mark: 6
    division: 9
rank:
    star0: 899
    star1: 1180
    star2: 1550
    star3: 1826
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 297.4
    acceleration: 73.39
    handling: 50.08
    nitro: 51.2
    average: 118.02
statMin:
    speed: 280.0
    acceleration: 63.1
    handling: 44.02
    nitro: 39.88
    average: 106.75
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 16
    rare: 4
    epic: 4
settingBlueprint:
    star1: '20'
    star2: 20
    star3: 50
    star4: 0
    star5: 0
    star6: 0
    total: 90
settingBrand:
    name: BMW
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 10
    common: 16
    rare: 4
    epic: 4
settingUnitPrice:
    level01: 1500
    level02: 2400
    level03: 3900
    level04: 5900
    level05: 8500
    level06: 12000
    level07: 16500
    level08: 23000
    level09: 32500
    level10: 45500
    level11: null
    level12: null
    level13: null
    common: 10000
    rare: 20000
    epic: 60000
