id: 114
stars: 6
gameUpdate: 16
carOrder: 59
statOrder: 17
level: 8
epic: 2
model: 'La Voiture Noire'
slug: bugatti-la-voiture-noire
blueprint:
    star1: '0'
    star2: 40
    star3: 45
    star4: 16
    star5: 0
    star6: 0
    total: 101
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 2
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3819
    star1: 3980
    star2: 4164
    star3: 4363
    star4: 4569
    star5: 4814
    star6: 5041
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 443.4
    acceleration: 84.89
    handling: 54.63
    nitro: 63.79
    average: 161.68
statMin:
    speed: 420.0
    acceleration: 78.4
    handling: 47.5
    nitro: 44.0
    average: 147.48
upgrade:
    speed: 8
    acceleration: 8
    handling: 8
    nitro: 8
    common: 24
    rare: 8
    epic: 0
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: Bugatti
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
