id: 7
stars: 6
gameUpdate: 0
carOrder: 39
statOrder: 23
level: 13
epic: 16
model: Chiron
slug: bugatti-chiron
blueprint:
    star1: '60'
    star2: 13
    star3: 16
    star4: 25
    star5: 38
    star6: 48
    total: 200
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 2
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3577
    star1: 3730
    star2: 3910
    star3: 4101
    star4: 4302
    star5: 4534
    star6: 4755
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 443.4
    acceleration: 84.4
    handling: 45.62
    nitro: 63.63
    average: 159.26
statMin:
    speed: 420.0
    acceleration: 77.5
    handling: 38.75
    nitro: 53.33
    average: 147.4
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 28
    rare: 20
    epic: 16
settingBlueprint:
    star1: '60'
    star2: 13
    star3: 16
    star4: 25
    star5: 38
    star6: 48
    total: 200
settingBrand:
    name: Bugatti
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
