id: 136
stars: 6
gameUpdate: 20
carOrder: 19
statOrder: 63
level: 3
epic: 7
model: 'Veyron 16.4 Grand Sport Vitesse'
slug: bugatti-veyron-16-4-grand-sport-vitesse
blueprint:
    star1: '85'
    star2: 19
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 104
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3111
    star1: 3281
    star2: 3480
    star3: 3693
    star4: 3910
    star5: 4165
    star6: 4406
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 419.0
    acceleration: 81.06
    handling: 49.15
    nitro: 50.72
    average: 149.98
statMin:
    speed: 410.0
    acceleration: 76.6
    handling: 40.2
    nitro: 37.0
    average: 140.95
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Bugatti
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
