id: 220
stars: 6
gameUpdate: 33
carOrder: 57
statOrder: 20
level: 8
epic: 10
model: 'Chiron Super Sport 300+'
slug: bugatti-chiron-super-sport-300
blueprint:
    star1: '0'
    star2: 40
    star3: 45
    star4: 43
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 2
    handling: 2
    nitro: 9
    mark: 3
    division: 9
rank:
    star0: 3770
    star1: 3924
    star2: 4106
    star3: 4303
    star4: 4514
    star5: 4762
    star6: 4983
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 456.6
    acceleration: 83.27
    handling: 60.63
    nitro: 41.7
    average: 160.55
statMin:
    speed: 440.0
    acceleration: 78.4
    handling: 41.54
    nitro: 24.79
    average: 146.18
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: Bugatti
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
