id: 175
stars: 6
gameUpdate: 26
carOrder: 48
statOrder: 41
level: 6
epic: 1
model: Centodieci
slug: bugatti-centodieci
blueprint:
    star1: '0'
    star2: 40
    star3: 22
    star4: 0
    star5: 0
    star6: 0
    total: 62
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 1
    handling: 3
    nitro: 1
    mark: 1
    division: 9
rank:
    star0: 3651
    star1: 3808
    star2: 3992
    star3: 4189
    star4: 4389
    star5: 4621
    star6: 4843
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 402.7
    acceleration: 86.51
    handling: 52.58
    nitro: 77.09
    average: 154.72
statMin:
    speed: 380.0
    acceleration: 78.57
    handling: 56.39
    nitro: 58.54
    average: 143.38
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: Bugatti
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
