id: 115
stars: 6
gameUpdate: 16
carOrder: 41
statOrder: 44
level: 6
epic: 3
model: Divo
slug: bugatti-divo
blueprint:
    star1: '85'
    star2: 25
    star3: 3
    star4: 0
    star5: 0
    star6: 0
    total: 113
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3601
    star1: 3755
    star2: 3935
    star3: 4126
    star4: 4324
    star5: 4553
    star6: 4773
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 396.0
    acceleration: 85.7
    handling: 61.48
    nitro: 73.99
    average: 154.29
statMin:
    speed: 380.0
    acceleration: 78.4
    handling: 52.2
    nitro: 57.07
    average: 141.92
upgrade:
    speed: 3
    acceleration: 2
    handling: 2
    nitro: 2
    common: 1
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Bugatti
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
