id: 259
stars: 6
gameUpdate: 39
carOrder: 50
statOrder: 14
level: 8
epic: 2
model: Mistral
slug: bugatti-mistral
blueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 21
    star5: 0
    star6: 0
    total: 160
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3041
    star1: 3278
    star2: 3558
    star3: 3856
    star4: 4163
    star5: 4522
    star6: 4859
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 459.8
    acceleration: 81.56
    handling: 57.68
    nitro: 50.42
    average: 162.36
statMin:
    speed: 420.0
    acceleration: 77.5
    handling: 50.12
    nitro: 30.0
    average: 144.41
upgrade:
    speed: 1
    acceleration: 1
    handling: 1
    nitro: 1
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Bugatti
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
