id: 96
stars: 5
gameUpdate: 13
carOrder: 41
statOrder: 32
level: 12
epic: 8
model: 'Corvette Stingray'
slug: chevrolet-corvette-stingray
blueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 28
    star5: 35
    star6: 0
    total: 134
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2176
    star1: 2381
    star2: 2677
    star3: 2937
    star4: 3250
    star5: 3787
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 327.7
    acceleration: 81.56
    handling: 60.15
    nitro: 64.44
    average: 133.46
statMin:
    speed: 312.0
    acceleration: 73.0
    handling: 45.3
    nitro: 48.59
    average: 119.72
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 16
    rare: 8
    epic: 0
settingBlueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 28
    star5: 35
    star6: 0
    total: 134
settingBrand:
    name: Chevrolet
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 12
    common: 36
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 7130
    level02: 11600
    level03: 18600
    level04: 27900
    level05: 40300
    level06: 56500
    level07: 79000
    level08: 110500
    level09: 155000
    level10: 216500
    level11: 303000
    level12: 425000
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
