id: 116
stars: 6
gameUpdate: 16
carOrder: 34
statOrder: 19
level: 13
epic: 16
model: 'GT by Citroën'
slug: citroen-gt-by-citroen
blueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 62
    total: 250
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 2907
    star1: 3085
    star2: 3292
    star3: 3483
    star4: 3739
    star5: 3989
    star6: 4222
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 388.7
    acceleration: 76.53
    handling: 64.61
    nitro: 67.2
    average: 149.26
statMin:
    speed: 375.0
    acceleration: 68.5
    handling: 55.71
    nitro: 50.08
    average: 137.32
upgrade:
    speed: 7
    acceleration: 7
    handling: 7
    nitro: 7
    common: 16
    rare: 4
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 62
    total: 250
settingBrand:
    name: Citroën
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
