id: 15
stars: 3
gameUpdate: 0
carOrder: 1
statOrder: 56
level: 10
epic: 4
model: 'Challenger SRT8'
slug: dodge-challenger-srt8
blueprint:
    star1: '15'
    star2: 20
    star3: 50
    star4: 0
    star5: 0
    star6: 0
    total: 85
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 9
    nitro: 3
    mark: 6
    division: 9
rank:
    star0: 799
    star1: 1075
    star2: 1425
    star3: 1687
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 308.6
    acceleration: 71.92
    handling: 39.84
    nitro: 46.24
    average: 116.65
statMin:
    speed: 292.0
    acceleration: 64.0
    handling: 26.47
    nitro: 23.08
    average: 101.39
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 16
    rare: 4
    epic: 4
settingBlueprint:
    star1: '15'
    star2: 20
    star3: 50
    star4: 0
    star5: 0
    star6: 0
    total: 85
settingBrand:
    name: Dodge
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 10
    common: 16
    rare: 4
    epic: 4
settingUnitPrice:
    level01: 1500
    level02: 2400
    level03: 3900
    level04: 5900
    level05: 8500
    level06: 12000
    level07: 16500
    level08: 23000
    level09: 32500
    level10: 45500
    level11: null
    level12: null
    level13: null
    common: 10000
    rare: 20000
    epic: 60000
