id: 13
stars: 4
gameUpdate: 0
carOrder: 13
statOrder: 27
level: 11
epic: 4
model: 'Viper ACR'
slug: dodge-viper-acr
blueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 32
    star5: 0
    star6: 0
    total: 103
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 1
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 1553
    star1: 1822
    star2: 2179
    star3: 2526
    star4: 2816
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 303.9
    acceleration: 77.32
    handling: 86.2
    nitro: 68.94
    average: 134.09
statMin:
    speed: 285.0
    acceleration: 68.5
    handling: 55.81
    nitro: 50.95
    average: 115.07
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 24
    rare: 12
    epic: 4
settingBlueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 32
    star5: 0
    star6: 0
    total: 103
settingBrand:
    name: Dodge
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 12
    epic: 4
settingUnitPrice:
    level01: 2530
    level02: 4100
    level03: 6600
    level04: 9900
    level05: 14300
    level06: 20000
    level07: 28000
    level08: 39000
    level09: 55000
    level10: 77000
    level11: 108000
    level12: null
    level13: null
    common: 15000
    rare: 30000
    epic: 90000
