id: 12
stars: 3
gameUpdate: 0
carOrder: 9
statOrder: 32
level: 10
epic: 0
model: 'Challenger Pack 392 Hemi Scat'
slug: dodge-challenger-pack-392-hemi-scat
blueprint:
    star1: '20'
    star2: 12
    star3: 30
    star4: 0
    star5: 0
    star6: 0
    total: 62
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 9
    handling: 3
    nitro: 2
    mark: 5
    division: 9
rank:
    star0: 899
    star1: 1337
    star2: 1757
    star3: 2144
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 299.3
    acceleration: 72.46
    handling: 43.24
    nitro: 62.34
    average: 119.34
statMin:
    speed: 283.0
    acceleration: 62.2
    handling: 36.1
    nitro: 50.71
    average: 108.0
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 20
    rare: 4
    epic: 0
settingBlueprint:
    star1: '20'
    star2: 12
    star3: 30
    star4: 0
    star5: 0
    star6: 0
    total: 62
settingBrand:
    name: Dodge
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 10
    common: 20
    rare: 4
    epic: 0
settingUnitPrice:
    level01: 1150
    level02: 1900
    level03: 3000
    level04: 4500
    level05: 6500
    level06: 9000
    level07: 12500
    level08: 18000
    level09: 25000
    level10: 35000
    level11: null
    level12: null
    level13: null
    common: 10000
    rare: 20000
    epic: 0
