id: 196
stars: 3
gameUpdate: 29
carOrder: 11
statOrder: 34
level: 10
epic: 4
model: 'D8 GTO'
slug: donkervoort-d8-gto
blueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 2
    handling: 1
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 1524
    star1: 1789
    star2: 2139
    star3: 2486
    star4: 2774
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 300.3
    acceleration: 85.42
    handling: 85.09
    nitro: 62.77
    average: 133.4
statMin:
    speed: 286.0
    acceleration: 76.6
    handling: 52.62
    nitro: 44.88
    average: 115.03
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
settingBrand:
    name: Donkervoort
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 12
    epic: 4
settingUnitPrice:
    level01: 5060
    level02: 8300
    level03: 13200
    level04: 19800
    level05: 28600
    level06: 40000
    level07: 56000
    level08: 78500
    level09: 110000
    level10: 154000
    level11: 215000
    level12: null
    level13: null
    common: 30000
    rare: 60000
    epic: 180000
