id: 141
stars: 4
gameUpdate: 21
carOrder: 22
statOrder: 53
level: 11
epic: 8
model: GTE
slug: drako-gte
blueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2141
    star1: 2376
    star2: 2741
    star3: 3102
    star4: 3425
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 346.2
    acceleration: 81.85
    handling: 47.31
    nitro: 61.18
    average: 134.14
statMin:
    speed: 332.0
    acceleration: 73.0
    handling: 39.97
    nitro: 48.8
    average: 123.44
upgrade:
    speed: 4
    acceleration: 4
    handling: 4
    nitro: 4
    common: 8
    rare: 0
    epic: 0
settingBlueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
settingBrand:
    name: Drako
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 5750
    level02: 9400
    level03: 15000
    level04: 22500
    level05: 32500
    level06: 45500
    level07: 63500
    level08: 89000
    level09: 125000
    level10: 175000
    level11: 245000
    level12: null
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
