id: 16
stars: 3
gameUpdate: 0
carOrder: 8
statOrder: 10
level: 10
epic: 0
model: 'DS E-Tense'
slug: ds-automobiles-ds-e-tense
blueprint:
    star1: '20'
    star2: 12
    star3: 30
    star4: 0
    star5: 0
    star6: 0
    total: 62
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 9
    handling: 1
    nitro: 2
    mark: 5
    division: 9
rank:
    star0: 799
    star1: 1216
    star2: 1607
    star3: 1976
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 270.1
    acceleration: 76.07
    handling: 81.27
    nitro: 72.3
    average: 124.94
statMin:
    speed: 250.0
    acceleration: 59.5
    handling: 45.09
    nitro: 51.56
    average: 101.54
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 20
    rare: 4
    epic: 0
settingBlueprint:
    star1: '20'
    star2: 12
    star3: 30
    star4: 0
    star5: 0
    star6: 0
    total: 62
settingBrand:
    name: 'DS Automobiles'
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 10
    common: 20
    rare: 4
    epic: 0
settingUnitPrice:
    level01: 1150
    level02: 1900
    level03: 3000
    level04: 4500
    level05: 6500
    level06: 9000
    level07: 12500
    level08: 18000
    level09: 25000
    level10: 35000
    level11: null
    level12: null
    level13: null
    common: 10000
    rare: 20000
    epic: 0
