id: 17
stars: 3
gameUpdate: 0
carOrder: 5
statOrder: 70
level: 10
epic: 4
model: W70
slug: exotic-rides-w70
blueprint:
    star1: '40'
    star2: 30
    star3: 70
    star4: 0
    star5: 0
    star6: 0
    total: 140
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 3
    nitro: 3
    mark: 3
    division: 9
rank:
    star0: 1567
    star1: 1920
    star2: 2308
    star3: 2633
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 329.7
    acceleration: 80.21
    handling: 45.2
    nitro: 56.71
    average: 127.95
statMin:
    speed: 313.0
    acceleration: 73.9
    handling: 40.46
    nitro: 43.05
    average: 117.6
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 24
    rare: 16
    epic: 4
settingBlueprint:
    star1: '40'
    star2: 30
    star3: 70
    star4: 0
    star5: 0
    star6: 0
    total: 140
settingBrand:
    name: 'Exotic Rides'
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 4
settingUnitPrice:
    level01: 1840
    level02: 3000
    level03: 4800
    level04: 7200
    level05: 10400
    level06: 14500
    level07: 20500
    level08: 28500
    level09: 40000
    level10: 56000
    level11: null
    level12: null
    level13: null
    common: 15000
    rare: 30000
    epic: 90000
