id: 190
stars: 6
gameUpdate: 28
carOrder: 30
statOrder: 60
level: 8
epic: 3
model: FFZero1
slug: faraday-future-ffzero1
blueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 2
    star5: 0
    star6: 0
    total: 141
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 1
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3425
    star1: 3578
    star2: 3758
    star3: 3949
    star4: 4149
    star5: 4377
    star6: 4602
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 423.0
    acceleration: 86.06
    handling: 42.83
    nitro: 51.7
    average: 150.9
statMin:
    speed: 403.0
    acceleration: 82.0
    handling: 37.56
    nitro: 33.6
    average: 139.04
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: 'Faraday Future'
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
