id: 106
stars: 6
gameUpdate: 15
carOrder: 16
statOrder: 57
level: 13
epic: 16
model: 'SF90 Stradale'
slug: ferrari-sf90-stradale
blueprint:
    star1: '60'
    star2: 25
    star3: 30
    star4: 35
    star5: 45
    star6: 55
    total: 250
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 1
    handling: 1
    nitro: 2
    mark: 1
    division: 9
rank:
    star0: 2928
    star1: 3124
    star2: 3350
    star3: 3587
    star4: 3832
    star5: 4117
    star6: 4395
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 355.4
    acceleration: 86.83
    handling: 93.51
    nitro: 69.9
    average: 151.41
statMin:
    speed: 340.0
    acceleration: 77.5
    handling: 66.86
    nitro: 51.64
    average: 134.0
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 28
    rare: 20
    epic: 16
settingBlueprint:
    star1: '60'
    star2: 25
    star3: 30
    star4: 35
    star5: 45
    star6: 55
    total: 250
settingBrand:
    name: Ferrari
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
