id: 50
stars: 4
gameUpdate: 1
carOrder: 4
statOrder: 60
level: 11
epic: 8
model: J50
slug: ferrari-j50
blueprint:
    star1: '45'
    star2: 21
    star3: 28
    star4: 42
    star5: 0
    star6: 0
    total: 136
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2200
    star1: 2453
    star2: 2709
    star3: 3008
    star4: 3306
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 350.6
    acceleration: 80.41
    handling: 48.37
    nitro: 64.65
    average: 136.01
statMin:
    speed: 333.0
    acceleration: 73.9
    handling: 42.27
    nitro: 48.91
    average: 124.52
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 20
    rare: 20
    epic: 8
settingBlueprint:
    star1: '45'
    star2: 21
    star3: 28
    star4: 42
    star5: 0
    star6: 0
    total: 136
settingBrand:
    name: Ferrari
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 11
    common: 20
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 3220
    level02: 5300
    level03: 8400
    level04: 12600
    level05: 18200
    level06: 25500
    level07: 35500
    level08: 50000
    level09: 70000
    level10: 98000
    level11: 137000
    level12: null
    level13: null
    common: 25000
    rare: 50000
    epic: 150000
