id: 251
stars: 6
gameUpdate: 38
carOrder: 41
statOrder: 33
level: 8
epic: 0
model: 'SF90 XX Stradale'
slug: ferrari-sf90-xx-stradale
blueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 15
    star5: 0
    star6: 0
    total: 135
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2855
    star1: 3044
    star2: 3271
    star3: 3479
    star4: 3751
    star5: 4023
    star6: 4286
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 361.2
    acceleration: 85.73
    handling: 79.17
    nitro: 62.85
    average: 147.24
statMin:
    speed: 349.0
    acceleration: 79.3
    handling: 50.58
    nitro: 31.25
    average: 127.53
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: Ferrari
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 12
    common: 24
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
