id: 125
stars: 4
gameUpdate: 18
carOrder: 10
statOrder: 54
level: 11
epic: 8
model: Roma
slug: ferrari-roma
blueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 4
    division: 9
rank:
    star0: 1872
    star1: 2091
    star2: 2431
    star3: 2766
    star4: 3069
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 331.7
    acceleration: 77.45
    handling: 60.49
    nitro: 66.78
    average: 134.11
statMin:
    speed: 320.0
    acceleration: 69.4
    handling: 46.11
    nitro: 51.38
    average: 121.72
upgrade:
    speed: 9
    acceleration: 9
    handling: 9
    nitro: 9
    common: 20
    rare: 16
    epic: 2
settingBlueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
settingBrand:
    name: Ferrari
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 5750
    level02: 9400
    level03: 15000
    level04: 22500
    level05: 32500
    level06: 45500
    level07: 63500
    level08: 89000
    level09: 125000
    level10: 175000
    level11: 245000
    level12: null
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
