id: 63
stars: 5
gameUpdate: 6
carOrder: 13
statOrder: 50
level: 12
epic: 12
model: '812 Superfast'
slug: ferrari-812-superfast
blueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 51
    star6: 0
    total: 187
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2643
    star1: 2778
    star2: 2963
    star3: 3189
    star4: 3493
    star5: 3827
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 353.6
    acceleration: 81.13
    handling: 63.17
    nitro: 74.36
    average: 143.07
statMin:
    speed: 340.0
    acceleration: 73.9
    handling: 46.64
    nitro: 60.62
    average: 130.29
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 24
    rare: 20
    epic: 12
settingBlueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 51
    star6: 0
    total: 187
settingBrand:
    name: Ferrari
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 12
    common: 24
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9550
    level02: 15600
    level03: 24900
    level04: 37400
    level05: 54000
    level06: 75500
    level07: 105000
    level08: 148000
    level09: 207500
    level10: 290000
    level11: 406000
    level12: 569000
    level13: null
    common: 60000
    rare: 120000
    epic: 360000
