id: 294
stars: 5
gameUpdate: 44
carOrder: 38
statOrder: 34
level: 6
epic: 0
model: 'F12 Berlinetta'
slug: ferrari-f12-berlinetta
blueprint:
    star1: '25'
    star2: 30
    star3: 29
    star4: 0
    star5: 0
    star6: 0
    total: 84
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2421
    star1: 2632
    star2: 2931
    star3: 0
    star4: 0
    star5: 0
    star6: 3950
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 357.2
    acceleration: 81.86
    handling: 61.13
    nitro: 68.14
    average: 142.08
statMin:
    speed: 340.0
    acceleration: 72.1
    handling: 40.65
    nitro: 47.64
    average: 125.1
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '25'
    star2: 30
    star3: 35
    star4: 40
    star5: 50
    star6: 60
    total: 240
settingBrand:
    name: Ferrari
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 99999
    level02: 99999
    level03: 99999
    level04: 99999
    level05: 99999
    level06: 99999
    level07: 99999
    level08: 99999
    level09: 99999
    level10: 999999
    level11: 999999
    level12: 999999
    level13: 999999
    common: 99999
    rare: 999999
    epic: 999999
