id: 266
stars: 6
gameUpdate: 40
carOrder: 59
statOrder: 7
level: 6
epic: 4
model: '499P Modificata'
slug: ferrari-499p-modificata
blueprint:
    star1: '70'
    star2: 23
    star3: 17
    star4: 0
    star5: 0
    star6: 0
    total: 110
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 1
    nitro: 1
    mark: 1
    division: 9
rank:
    star0: 3227
    star1: 3450
    star2: 3652
    star3: 3840
    star4: 4085
    star5: 4333
    star6: 4572
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 358.6
    acceleration: 84.54
    handling: 85.32
    nitro: 77.85
    average: 151.58
statMin:
    speed: 340.0
    acceleration: 75.7
    handling: 51.89
    nitro: 51.64
    average: 129.81
upgrade:
    speed: 4
    acceleration: 4
    handling: 4
    nitro: 4
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: Ferrari
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
