id: 253
stars: 4
gameUpdate: 38
carOrder: 9
statOrder: 60
level: 0
epic: 0
model: 'Mustang RTR Spec 5 10th Anniversary'
slug: ford-mustang-rtr-spec-5-10th-anniversary
blueprint:
    star1: '14'
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 14
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 2
    mark: 4
    division: 9
rank:
    star0: 1840
    star1: 2059
    star2: 2398
    star3: 2731
    star4: 3025
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 335.2
    acceleration: 75.65
    handling: 46.89
    nitro: 73.82
    average: 132.89
statMin:
    speed: 322.0
    acceleration: 67.6
    handling: 39.11
    nitro: 63.13
    average: 122.96
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
settingBrand:
    name: Ford
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 5750
    level02: 9400
    level03: 15000
    level04: 22500
    level05: 32500
    level06: 45500
    level07: 63500
    level08: 89000
    level09: 125000
    level10: 175000
    level11: 245000
    level12: null
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
