id: 303
stars: 6
gameUpdate: 45
carOrder: 35
statOrder: 36
level: 8
epic: 8
model: 'Mustang RTR Spec 5-FD'
slug: ford-mustang-rtr-spec-5-fd
blueprint:
    star1: '35'
    star2: 40
    star3: 45
    star4: 36
    star5: 0
    star6: 0
    total: 156
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 9
    handling: 3
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 0
    star1: 0
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 415.0
    acceleration: 78.77
    handling: 54.9
    nitro: 74.41
    average: 155.77
statMin:
    speed: 403.0
    acceleration: 73.9
    handling: 46.04
    nitro: 58.48
    average: 145.36
upgrade:
    speed: 8
    acceleration: 8
    handling: 8
    nitro: 8
    common: 16
    rare: 8
    epic: 0
settingBlueprint:
    star1: '35'
    star2: 40
    star3: 45
    star4: 50
    star5: 60
    star6: 70
    total: 300
settingBrand:
    name: Ford
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
