id: 98
stars: 4
gameUpdate: 13
carOrder: 15
statOrder: 49
level: 11
epic: 6
model: 'GT MK II'
slug: ford-gt-mk-ii
blueprint:
    star1: Key
    star2: 35
    star3: 55
    star4: 85
    star5: 0
    star6: 0
    total: 175
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 1970
    star1: 2199
    star2: 2552
    star3: 2898
    star4: 3200
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 315.5
    acceleration: 86.26
    handling: 79.0
    nitro: 67.88
    average: 137.16
statMin:
    speed: 300.0
    acceleration: 76.6
    handling: 57.8
    nitro: 49.12
    average: 120.88
upgrade:
    speed: 9
    acceleration: 9
    handling: 9
    nitro: 9
    common: 24
    rare: 14
    epic: 0
settingBlueprint:
    star1: Key
    star2: 35
    star3: 55
    star4: 85
    star5: 0
    star6: 0
    total: 175
settingBrand:
    name: Ford
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 5750
    level02: 9400
    level03: 15000
    level04: 22500
    level05: 32500
    level06: 45500
    level07: 63500
    level08: 89000
    level09: 125000
    level10: 175000
    level11: 245000
    level12: null
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
