id: 267
stars: 6
gameUpdate: 40
carOrder: 48
statOrder: 37
level: 10
epic: 2
model: 'Shelby Super Snake'
slug: ford-shelby-super-snake
blueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 46
    star6: 0
    total: 202
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3046
    star1: 3218
    star2: 3422
    star3: 3609
    star4: 3857
    star5: 4106
    star6: 4350
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 363.4
    acceleration: 85.44
    handling: 75.98
    nitro: 59.74
    average: 146.14
statMin:
    speed: 346.8
    acceleration: 76.6
    handling: 56.43
    nitro: 34.15
    average: 128.5
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: Ford
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
