id: 23
stars: 4
gameUpdate: 0
carOrder: 7
statOrder: 61
level: 11
epic: 8
model: GT
slug: ford-gt
blueprint:
    star1: '30'
    star2: 23
    star3: 54
    star4: 0
    star5: 0
    star6: 0
    total: 107
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 9
    nitro: 3
    mark: 5
    division: 9
rank:
    star0: 1685
    star1: 1895
    star2: 2216
    star3: 2535
    star4: 2816
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 362.8
    acceleration: 79.15
    handling: 34.36
    nitro: 54.49
    average: 132.7
statMin:
    speed: 348.0
    acceleration: 70.3
    handling: 29.92
    nitro: 38.29
    average: 121.63
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 24
    rare: 16
    epic: 8
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 54
    star4: 0
    star5: 0
    star6: 0
    total: 107
settingBrand:
    name: Ford
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 2880
    level02: 4700
    level03: 7500
    level04: 11300
    level05: 16300
    level06: 23000
    level07: 32000
    level08: 44500
    level09: 62500
    level10: 87500
    level11: 122000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
