id: 252
stars: 5
gameUpdate: 38
carOrder: 19
statOrder: 38
level: 6
epic: 0
model: 'GT Frankie Edition'
slug: ford-gt-frankie-edition
blueprint:
    star1: '50'
    star2: 23
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 73
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 3
    nitro: 2
    mark: 4
    division: 9
rank:
    star0: 2743
    star1: 2883
    star2: 3076
    star3: 3317
    star4: 3809
    star5: 3974
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 371.8
    acceleration: 79.14
    handling: 58.82
    nitro: 74.63
    average: 146.1
statMin:
    speed: 355.3
    acceleration: 70.3
    handling: 45.82
    nitro: 57.42
    average: 132.21
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 51
    star6: 0
    total: 187
settingBrand:
    name: Ford
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 12
    common: 24
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9550
    level02: 15600
    level03: 24900
    level04: 37400
    level05: 54000
    level06: 75500
    level07: 105000
    level08: 148000
    level09: 207500
    level10: 290000
    level11: 406000
    level12: 569000
    level13: null
    common: 60000
    rare: 120000
    epic: 360000
