id: 286
stars: 5
gameUpdate: 43
carOrder: 34
statOrder: 45
level: 12
epic: 8
model: 'GEN 3 EVO Championship Edition'
slug: formule-e-gen-3-evo-championship-edition
blueprint:
    star1: Key
    star2: 35
    star3: 40
    star4: 50
    star5: 55
    star6: 0
    total: 180
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 2
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 2468
    star1: 2658
    star2: 2935
    star3: 3181
    star4: 3533
    star5: 3871
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 335.4
    acceleration: 90.29
    handling: 71.21
    nitro: 59.35
    average: 139.06
statMin:
    speed: 322.0
    acceleration: 83.62
    handling: 46.32
    nitro: 41.99
    average: 123.48
upgrade:
    speed: 10
    acceleration: 10
    handling: 11
    nitro: 12
    common: 31
    rare: 16
    epic: 4
settingBlueprint:
    star1: Key
    star2: 35
    star3: 40
    star4: 50
    star5: 55
    star6: 0
    total: 180
settingBrand:
    name: 'Formule E'
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
