id: 273
stars: 5
gameUpdate: 41
carOrder: 57
statOrder: 42
level: 8
epic: 2
model: GT65
slug: fv-frangivento-gt65
blueprint:
    star1: ''
    star2: 26
    star3: 34
    star4: 30
    star5: 0
    star6: 0
    total: 90
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 2319
    star1: 2564
    star2: 2738
    star3: 0
    star4: 0
    star5: 4171
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 371.1
    acceleration: 81.8
    handling: 51.98
    nitro: 54.39
    average: 139.82
statMin:
    speed: 355.0
    acceleration: 75.7
    handling: 34.21
    nitro: 26.49
    average: 122.85
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 26
    star3: 34
    star4: 40
    star5: 62
    star6: 0
    total: 162
settingBrand:
    name: 'FV Frangivento'
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
