id: 201
stars: 6
gameUpdate: 30
carOrder: 17
statOrder: 70
level: 6
epic: 3
model: 'Sorpasso GT3'
slug: fv-frangivento-sorpasso-gt3
blueprint:
    star1: '0'
    star2: 40
    star3: 1
    star4: 0
    star5: 0
    star6: 0
    total: 41
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3277
    star1: 3420
    star2: 3591
    star3: 3771
    star4: 3963
    star5: 4190
    star6: 4398
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 391.3
    acceleration: 85.7
    handling: 56.68
    nitro: 47.35
    average: 145.26
statMin:
    speed: 382.2
    acceleration: 78.4
    handling: 48.34
    nitro: 17.08
    average: 131.51
upgrade:
    speed: 3
    acceleration: 3
    handling: 3
    nitro: 3
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: 'FV Frangivento'
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
