id: 64
stars: 4
gameUpdate: 6
carOrder: 26
statOrder: 11
level: 11
epic: 4
model: G60
slug: ginetta-g60
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 5
    division: 9
rank:
    star0: 1181
    star1: 1517
    star2: 1891
    star3: 2277
    star4: 2646
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 290.7
    acceleration: 71.51
    handling: 74.81
    nitro: 62.66
    average: 124.92
statMin:
    speed: 275.0
    acceleration: 57.7
    handling: 54.48
    nitro: 46.29
    average: 108.37
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 28
    rare: 8
    epic: 4
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Ginetta
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
