id: 150
stars: 5
gameUpdate: 22
carOrder: 40
statOrder: 3
level: 12
epic: 8
model: 004C
slug: glickenhaus-004c
blueprint:
    star1: Key
    star2: 22
    star3: 30
    star4: 35
    star5: 38
    star6: 0
    total: 125
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 2
    mark: 4
    division: 9
rank:
    star0: 1524
    star1: 1726
    star2: 1964
    star3: 2217
    star4: 2550
    star5: 3075
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 311.2
    acceleration: 76.75
    handling: 56.89
    nitro: 60.87
    average: 126.43
statMin:
    speed: 298.0
    acceleration: 70.3
    handling: 40.47
    nitro: 36.15
    average: 111.23
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 36
    rare: 16
    epic: 8
settingBlueprint:
    star1: Key
    star2: 22
    star3: 30
    star4: 35
    star5: 38
    star6: 0
    total: 125
settingBrand:
    name: Glickenhaus
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 12
    common: 36
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 6440
    level02: 10500
    level03: 16800
    level04: 25200
    level05: 36400
    level06: 51000
    level07: 71500
    level08: 100000
    level09: 140000
    level10: 196000
    level11: 274000
    level12: 384000
    level13: null
    common: 15000
    rare: 30000
    epic: 90000
