id: 151
stars: 6
gameUpdate: 22
carOrder: 33
statOrder: 36
level: 13
epic: 16
model: 007S
slug: glickenhaus-007s
blueprint:
    star1: Key
    star2: 28
    star3: 32
    star4: 44
    star5: 59
    star6: 86
    total: 249
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 1
    handling: 1
    nitro: 3
    mark: 1
    division: 9
rank:
    star0: 2653
    star1: 2859
    star2: 3101
    star3: 3325
    star4: 3613
    star5: 3902
    star6: 4187
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 358.6
    acceleration: 89.33
    handling: 82.63
    nitro: 55.24
    average: 146.45
statMin:
    speed: 340.0
    acceleration: 82.9
    handling: 59.38
    nitro: 61.67
    average: 135.99
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 24
    rare: 20
    epic: 16
settingBlueprint:
    star1: Key
    star2: 28
    star3: 32
    star4: 44
    star5: 59
    star6: 86
    total: 249
settingBrand:
    name: Glickenhaus
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
