id: 137
stars: 6
gameUpdate: 20
carOrder: 66
statOrder: 5
level: 6
epic: 2
model: 'Venom F5'
slug: hennessey-venom-f5
blueprint:
    star1: '85'
    star2: 25
    star3: 16
    star4: 0
    star5: 0
    star6: 0
    total: 126
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3881
    star1: 4046
    star2: 4237
    star3: 4439
    star4: 4651
    star5: 4900
    star6: 5126
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 512.3
    acceleration: 80.66
    handling: 49.07
    nitro: 49.53
    average: 172.89
statMin:
    speed: 500.0
    acceleration: 76.6
    handling: 41.76
    nitro: 27.93
    average: 161.57
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Hennessey
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
