id: 274
stars: 6
gameUpdate: 41
carOrder: 55
statOrder: 13
level: 3
epic: 1
model: 'Locus Pléthore LC750'
slug: htt-locus-plethore-lc750
blueprint:
    star1: '85'
    star2: 7
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 92
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 9
    handling: 2
    nitro: 1
    mark: 3
    division: 9
rank:
    star0: 3746
    star1: 3901
    star2: 4083
    star3: 4278
    star4: 4481
    star5: 4730
    star6: 4955
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 414.5
    acceleration: 78.04
    handling: 75.86
    nitro: 84.58
    average: 163.25
statMin:
    speed: 398.0
    acceleration: 74.8
    handling: 59.9
    nitro: 55.7
    average: 147.1
upgrade:
    speed: 1
    acceleration: 1
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: HTT
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
