id: 280
stars: 4
gameUpdate: 42
carOrder: 22
statOrder: 31
level: 9
epic: 1
model: 'Ioniq 5 N'
slug: hyundai-ioniq-5-n
blueprint:
    star1: '15'
    star2: 25
    star3: 35
    star4: 44
    star5: 0
    star6: 0
    total: 119
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 2
    handling: 2
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 1034
    star1: 1391
    star2: 1782
    star3: 2183
    star4: 2559
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 271.4
    acceleration: 85.03
    handling: 70.08
    nitro: 51.35
    average: 119.46
statMin:
    speed: 260.0
    acceleration: 75.03
    handling: 41.28
    nitro: 18.03
    average: 98.58
upgrade:
    speed: 9
    acceleration: 9
    handling: 9
    nitro: 9
    common: 22
    rare: 8
    epic: 0
settingBlueprint:
    star1: '15'
    star2: 25
    star3: 35
    star4: 50
    star5: 0
    star6: 0
    total: 125
settingBrand:
    name: Hyundai
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
