id: 25
stars: 5
gameUpdate: 0
carOrder: 4
statOrder: 71
level: 12
epic: 12
model: 'Vulcano Titanium'
slug: icona-vulcano-titanium
blueprint:
    star1: '40'
    star2: 13
    star3: 16
    star4: 25
    star5: 39
    star6: 0
    total: 133
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2907
    star1: 3058
    star2: 3238
    star3: 3412
    star4: 3682
    star5: 3957
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 381.7
    acceleration: 81.38
    handling: 43.38
    nitro: 65.89
    average: 143.09
statMin:
    speed: 370.0
    acceleration: 75.7
    handling: 35.26
    nitro: 53.84
    average: 133.7
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 28
    rare: 20
    epic: 12
settingBlueprint:
    star1: '40'
    star2: 13
    star3: 16
    star4: 25
    star5: 39
    star6: 0
    total: 133
settingBrand:
    name: Icona
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 12
    common: 28
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
