id: 122
stars: 4
gameUpdate: 17
carOrder: 16
statOrder: 24
level: 11
epic: 4
model: 'Projet Black S'
slug: infiniti-projet-black-s
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 5
    division: 9
rank:
    star0: 729
    star1: 1119
    star2: 1540
    star3: 1970
    star4: 2368
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 281.2
    acceleration: 76.19
    handling: 66.97
    nitro: 64.68
    average: 122.26
statMin:
    speed: 246.2
    acceleration: 64.0
    handling: 47.65
    nitro: 44.65
    average: 100.62
upgrade:
    speed: 6
    acceleration: 9
    handling: 6
    nitro: 6
    common: 16
    rare: 2
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Infiniti
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
