id: 214
stars: 4
gameUpdate: 32
carOrder: 23
statOrder: 36
level: 4
epic: 0
model: XJR-15
slug: jaguar-xjr-15
blueprint:
    star1: '50'
    star2: 16
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 66
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 1840
    star1: 2135
    star2: 2523
    star3: 2907
    star4: 3221
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 320.4
    acceleration: 80.82
    handling: 70.91
    nitro: 61.06
    average: 133.3
statMin:
    speed: 307.0
    acceleration: 71.2
    handling: 48.28
    nitro: 44.33
    average: 117.7
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
settingBrand:
    name: Jaguar
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 10
    common: 16
    rare: 4
    epic: 4
settingUnitPrice:
    level01: 5060
    level02: 8300
    level03: 13200
    level04: 19800
    level05: 28600
    level06: 40000
    level07: 56000
    level08: 78500
    level09: 110000
    level10: 154000
    level11: 215000
    level12: null
    level13: null
    common: 30000
    rare: 60000
    epic: 180000
