id: 268
stars: 4
gameUpdate: 40
carOrder: 9
statOrder: 48
level: 11
epic: 0
model: 'XKR-S GT'
slug: jaguar-xkr-s-gt
blueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 2
    mark: 4
    division: 9
rank:
    star0: 1346
    star1: 1636
    star2: 2019
    star3: 2395
    star4: 2700
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 321.2
    acceleration: 72.92
    handling: 52.08
    nitro: 60.42
    average: 126.66
statMin:
    speed: 300.0
    acceleration: 64.9
    handling: 38.6
    nitro: 36.32
    average: 109.96
upgrade:
    speed: 8
    acceleration: 8
    handling: 8
    nitro: 8
    common: 20
    rare: 2
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
settingBrand:
    name: Jaguar
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 12
    epic: 4
settingUnitPrice:
    level01: 5060
    level02: 8300
    level03: 13200
    level04: 19800
    level05: 28600
    level06: 40000
    level07: 56000
    level08: 78500
    level09: 110000
    level10: 154000
    level11: 215000
    level12: null
    level13: null
    common: 30000
    rare: 60000
    epic: 180000
