id: 202
stars: 3
gameUpdate: 30
carOrder: 56
statOrder: 2
level: 10
epic: 4
model: XJR-9
slug: jaguar-xjr-9
blueprint:
    star1: '0'
    star2: 30
    star3: 40
    star4: 31
    star5: 0
    star6: 0
    total: 101
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 9
    handling: 3
    nitro: 1
    mark: 3
    division: 9
rank:
    star0: 3261
    star1: 3433
    star2: 3634
    star3: 3821
    star4: 4066
    star5: 4311
    star6: 4551
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 412.3
    acceleration: 69.24
    handling: 59.33
    nitro: 84.95
    average: 156.46
statMin:
    speed: 394.0
    acceleration: 60.4
    handling: 53.61
    nitro: 64.18
    average: 143.05
upgrade:
    speed: 5
    acceleration: 5
    handling: 5
    nitro: 5
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 30
    star3: 40
    star4: 50
    star5: 65
    star6: 80
    total: 265
settingBrand:
    name: Jaguar
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
