id: 26
stars: 4
gameUpdate: 0
carOrder: 3
statOrder: 68
level: 11
epic: 8
model: 'F-Type SVR'
slug: jaguar-f-type-svr
blueprint:
    star1: '30'
    star2: 18
    star3: 24
    star4: 36
    star5: 0
    star6: 0
    total: 108
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 1454
    star1: 1645
    star2: 1943
    star3: 2237
    star4: 2500
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 341.0
    acceleration: 75.55
    handling: 49.28
    nitro: 50.12
    average: 128.99
statMin:
    speed: 322.0
    acceleration: 66.7
    handling: 43.33
    nitro: 34.31
    average: 116.59
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 24
    rare: 4
    epic: 8
settingBlueprint:
    star1: '30'
    star2: 18
    star3: 24
    star4: 36
    star5: 0
    star6: 0
    total: 108
settingBrand:
    name: Jaguar
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 10
    common: 24
    rare: 4
    epic: 8
settingUnitPrice:
    level01: 2880
    level02: 4700
    level03: 7500
    level04: 11300
    level05: 16300
    level06: 23000
    level07: 32000
    level08: 44500
    level09: 62500
    level10: 87500
    level11: 122000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
