id: 203
stars: 3
gameUpdate: 30
carOrder: 21
statOrder: 56
level: 3
epic: 1
model: Motion
slug: kepler-motion
blueprint:
    star1: '55'
    star2: 25
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 80
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2106
    star1: 2342
    star2: 2708
    star3: 3067
    star4: 3380
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 338.5
    acceleration: 86.45
    handling: 48.72
    nitro: 61.18
    average: 133.71
statMin:
    speed: 322.0
    acceleration: 78.4
    handling: 40.55
    nitro: 40.07
    average: 120.26
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
settingBrand:
    name: Kepler
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 5750
    level02: 9400
    level03: 15000
    level04: 22500
    level05: 32500
    level06: 45500
    level07: 63500
    level08: 89000
    level09: 125000
    level10: 175000
    level11: 245000
    level12: null
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
