id: 275
stars: 5
gameUpdate: 41
carOrder: 43
statOrder: 1
level: 8
epic: 3
model: EVO37
slug: kimera-evo37
blueprint:
    star1: ''
    star2: 22
    star3: 30
    star4: 18
    star5: 0
    star6: 0
    total: 70
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 3
    handling: 2
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 1545
    star1: 1747
    star2: 1986
    star3: 2251
    star4: 2574
    star5: 3108
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 297.8
    acceleration: 80.98
    handling: 78.18
    nitro: 57.43
    average: 128.6
statMin:
    speed: 280.0
    acceleration: 72.1
    handling: 64.96
    nitro: 34.65
    average: 112.93
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 22
    star3: 30
    star4: 35
    star5: 38
    star6: 0
    total: 125
settingBrand:
    name: Kimera
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 12
    common: 28
    rare: 12
    epic: 8
settingUnitPrice:
    level01: 6440
    level02: 10500
    level03: 16800
    level04: 25200
    level05: 36400
    level06: 51000
    level07: 71500
    level08: 100000
    level09: 140000
    level10: 196000
    level11: 274000
    level12: 384000
    level13: null
    common: 15000
    rare: 30000
    epic: 90000
