id: 152
stars: 6
gameUpdate: 22
carOrder: 64
statOrder: 46
level: 13
epic: 4
model: Gemera
slug: koenigsegg-gemera
blueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 1
    handling: 2
    nitro: 3
    mark: 1
    division: 9
rank:
    star0: 3856
    star1: 4018
    star2: 4207
    star3: 4409
    star4: 4616
    star5: 4864
    star6: 5085
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 413.1
    acceleration: 88.58
    handling: 66.06
    nitro: 48.36
    average: 154.03
statMin:
    speed: 400.0
    acceleration: 82.9
    handling: 50.01
    nitro: 28.93
    average: 140.46
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 28
    rare: 20
    epic: 4
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: Koenigsegg
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
