id: 65
stars: 6
gameUpdate: 6
carOrder: 46
statOrder: 9
level: 13
epic: 10
model: Jesko
slug: koenigsegg-jesko
blueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3637
    star1: 3793
    star2: 3975
    star3: 4170
    star4: 4372
    star5: 4608
    star6: 4826
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 496.6
    acceleration: 80.07
    handling: 48.19
    nitro: 58.23
    average: 170.77
statMin:
    speed: 484.0
    acceleration: 74.8
    handling: 41.93
    nitro: 42.56
    average: 160.82
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 28
    rare: 20
    epic: 8
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: Koenigsegg
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
