id: 205
stars: 3
gameUpdate: 30
carOrder: 6
statOrder: 38
level: 10
epic: 0
model: 'X-Bow GTX'
slug: ktm-x-bow-gtx
blueprint:
    star1: '30'
    star2: 23
    star3: 54
    star4: 0
    star5: 0
    star6: 0
    total: 107
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 2
    handling: 2
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 662
    star1: 1042
    star2: 1398
    star3: 1738
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 247.5
    acceleration: 83.84
    handling: 64.99
    nitro: 66.99
    average: 115.83
statMin:
    speed: 231.0
    acceleration: 64.9
    handling: 42.69
    nitro: 50.35
    average: 97.24
upgrade:
    speed: 5
    acceleration: 6
    handling: 5
    nitro: 5
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 54
    star4: 0
    star5: 0
    star6: 0
    total: 107
settingBrand:
    name: KTM
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 10
    common: 20
    rare: 4
    epic: 0
settingUnitPrice:
    level01: 1150
    level02: 1900
    level03: 3000
    level04: 4500
    level05: 6500
    level06: 9000
    level07: 12500
    level08: 18000
    level09: 25000
    level10: 35000
    level11: null
    level12: null
    level13: null
    common: 10000
    rare: 20000
    epic: 0
