id: 255
stars: 6
gameUpdate: 38
carOrder: 3
statOrder: 75
level: 8
epic: 3
model: Autentica
slug: lamborghini-autentica
blueprint:
    star1: Key
    star2: 35
    star3: 36
    star4: 21
    star5: 0
    star6: 0
    total: 92
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 3
    nitro: 2
    mark: 4
    division: 9
rank:
    star0: 2855
    star1: 3005
    star2: 3180
    star3: 3352
    star4: 3620
    star5: 3894
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 366.9
    acceleration: 78.86
    handling: 47.25
    nitro: 68.87
    average: 140.47
statMin:
    speed: 355.0
    acceleration: 74.8
    handling: 41.94
    nitro: 53.27
    average: 131.25
upgrade:
    speed: 3
    acceleration: 3
    handling: 3
    nitro: 3
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 35
    star3: 36
    star4: 46
    star5: 85
    star6: 0
    total: 202
settingBrand:
    name: Lamborghini
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 12
    common: 28
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 11500
    level02: 18800
    level03: 30000
    level04: 45000
    level05: 65000
    level06: 91000
    level07: 127500
    level08: 178500
    level09: 249500
    level10: 349500
    level11: 489000
    level12: 685000
    level13: null
    common: 70000
    rare: 140000
    epic: 420000
