id: 117
stars: 5
gameUpdate: 16
carOrder: 38
statOrder: 5
level: 12
epic: 7
model: 'Huracán Super Trofeo Evo'
slug: lamborghini-huracan-super-trofeo-evo
blueprint:
    star1: Key
    star2: 22
    star3: 30
    star4: 35
    star5: 38
    star6: 0
    total: 125
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 2
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 1475
    star1: 1673
    star2: 1905
    star3: 2160
    star4: 2479
    star5: 3000
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 303.7
    acceleration: 82.89
    handling: 63.48
    nitro: 54.41
    average: 126.12
statMin:
    speed: 290.0
    acceleration: 72.1
    handling: 46.42
    nitro: 31.01
    average: 109.88
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 32
    rare: 16
    epic: 7
settingBlueprint:
    star1: Key
    star2: 22
    star3: 30
    star4: 35
    star5: 38
    star6: 0
    total: 125
settingBrand:
    name: Lamborghini
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 12
    common: 32
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 6440
    level02: 10500
    level03: 16800
    level04: 25200
    level05: 36400
    level06: 51000
    level07: 71500
    level08: 100000
    level09: 140000
    level10: 196000
    level11: 274000
    level12: 384000
    level13: null
    common: 15000
    rare: 30000
    epic: 90000
