id: 170
stars: 5
gameUpdate: 25
carOrder: 41
statOrder: 24
level: 10
epic: 3
model: 'Reventón Roadster'
slug: lamborghini-reventon-roadster
blueprint:
    star1: Key
    star2: 26
    star3: 34
    star4: 40
    star5: 17
    star6: 0
    total: 117
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 2555
    star1: 2747
    star2: 3021
    star3: 3266
    star4: 3622
    star5: 3984
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 356.3
    acceleration: 78.35
    handling: 67.65
    nitro: 74.41
    average: 144.18
statMin:
    speed: 340.0
    acceleration: 69.4
    handling: 51.14
    nitro: 55.63
    average: 129.04
upgrade:
    speed: 8
    acceleration: 8
    handling: 8
    nitro: 8
    common: 26
    rare: 6
    epic: 0
settingBlueprint:
    star1: Key
    star2: 26
    star3: 34
    star4: 40
    star5: 62
    star6: 0
    total: 162
settingBrand:
    name: Lamborghini
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
