id: 90
stars: 5
gameUpdate: 12
carOrder: 51
statOrder: 4
level: 12
epic: 8
model: 'Gallardo LP560-4'
slug: lamborghini-gallardo-lp560-4
blueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 28
    star5: 35
    star6: 0
    total: 134
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 2
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 2301
    star1: 2521
    star2: 2830
    star3: 3102
    star4: 3438
    star5: 3997
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 340.7
    acceleration: 76.56
    handling: 75.81
    nitro: 59.69
    average: 138.19
statMin:
    speed: 325.0
    acceleration: 67.6
    handling: 50.25
    nitro: 38.4
    average: 120.31
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 36
    rare: 16
    epic: 1
settingBlueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 28
    star5: 35
    star6: 0
    total: 134
settingBrand:
    name: Lamborghini
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 12
    common: 36
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 7130
    level02: 11600
    level03: 18600
    level04: 27900
    level05: 40300
    level06: 56500
    level07: 79000
    level08: 110500
    level09: 155000
    level10: 216500
    level11: 303000
    level12: 425000
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
