id: 28
stars: 6
gameUpdate: 0
carOrder: 20
statOrder: 64
level: 13
epic: 16
model: 'Terzo Millennio'
slug: lamborghini-terzo-millennio
blueprint:
    star1: '60'
    star2: 13
    star3: 16
    star4: 25
    star5: 38
    star6: 48
    total: 200
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3288
    star1: 3440
    star2: 3618
    star3: 3798
    star4: 3986
    star5: 4205
    star6: 4411
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 394.3
    acceleration: 82.77
    handling: 52.84
    nitro: 69.29
    average: 149.8
statMin:
    speed: 380.8
    acceleration: 78.19
    handling: 45.16
    nitro: 54.79
    average: 139.73
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 28
    rare: 20
    epic: 16
settingBlueprint:
    star1: '60'
    star2: 13
    star3: 16
    star4: 25
    star5: 38
    star6: 48
    total: 200
settingBrand:
    name: Lamborghini
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
