id: 168
stars: 4
gameUpdate: 25
carOrder: 20
statOrder: 35
level: 11
epic: 4
model: 'Countach 25th Anniversary'
slug: lamborghini-countach-25th-anniversary
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 9
    mark: 6
    division: 9
rank:
    star0: 1063
    star1: 1389
    star2: 1757
    star3: 2135
    star4: 2498
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 304.9
    acceleration: 71.69
    handling: 55.89
    nitro: 36.3
    average: 117.2
statMin:
    speed: 293.0
    acceleration: 59.5
    handling: 43.38
    nitro: 14.14
    average: 102.51
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Lamborghini
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
