id: 59
stars: 5
gameUpdate: 4
carOrder: 55
statOrder: 7
level: 12
epic: 8
model: 'Huracán Evo Spyder'
slug: lamborghini-huracan-evo-spyder
blueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 2
    handling: 2
    nitro: 1
    mark: 2
    division: 9
rank:
    star0: 2004
    star1: 2291
    star2: 2706
    star3: 3075
    star4: 3604
    star5: 4109
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 344.0
    acceleration: 84.31
    handling: 75.97
    nitro: 82.43
    average: 146.68
statMin:
    speed: 325.0
    acceleration: 72.1
    handling: 46.62
    nitro: 51.94
    average: 123.92
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 32
    rare: 20
    epic: 8
settingBlueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
settingBrand:
    name: Lamborghini
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
