id: 91
stars: 6
gameUpdate: 12
carOrder: 40
statOrder: 32
level: 12
epic: 4
model: SC18
slug: lamborghini-sc18
blueprint:
    star1: Key
    star2: 28
    star3: 32
    star4: 44
    star5: 59
    star6: 36
    total: 199
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 2
    nitro: 1
    mark: 2
    division: 9
rank:
    star0: 2992
    star1: 3166
    star2: 3369
    star3: 3556
    star4: 3806
    star5: 4050
    star6: 4284
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 362.1
    acceleration: 82.03
    handling: 64.0
    nitro: 82.48
    average: 147.65
statMin:
    speed: 350.0
    acceleration: 74.8
    handling: 45.33
    nitro: 64.96
    average: 133.77
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 20
    rare: 16
    epic: 0
settingBlueprint:
    star1: Key
    star2: 28
    star3: 32
    star4: 44
    star5: 59
    star6: 86
    total: 249
settingBrand:
    name: Lamborghini
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
