id: 173
stars: 6
gameUpdate: 25
carOrder: 60
statOrder: 17
level: 13
epic: 12
model: 'Sesto Elemento'
slug: lamborghini-sesto-elemento
blueprint:
    star1: '55'
    star2: 18
    star3: 24
    star4: 32
    star5: 47
    star6: 50
    total: 226
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2029
    star1: 2295
    star2: 2605
    star3: 2917
    star4: 3343
    star5: 3833
    star6: 4183
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 346.5
    acceleration: 87.26
    handling: 70.27
    nitro: 74.76
    average: 144.7
statMin:
    speed: 325.0
    acceleration: 77.5
    handling: 40.46
    nitro: 44.2
    average: 121.79
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 22
    rare: 1
    epic: 0
settingBlueprint:
    star1: '55'
    star2: 18
    star3: 24
    star4: 32
    star5: 47
    star6: 50
    total: 226
settingBrand:
    name: Lamborghini
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 13
    common: 32
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9890
    level02: 16100
    level03: 25800
    level04: 38700
    level05: 55900
    level06: 78500
    level07: 109500
    level08: 153500
    level09: 214500
    level10: 300500
    level11: 421000
    level12: 589000
    level13: 967500
    common: 70000
    rare: 140000
    epic: 420000
