id: 138
stars: 6
gameUpdate: 20
carOrder: 21
statOrder: 27
level: 13
epic: 16
model: 'Aventador SVJ Roadster'
slug: lamborghini-aventador-svj-roadster
blueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2274
    star1: 2515
    star2: 2800
    star3: 3062
    star4: 3405
    star5: 3748
    star6: 4081
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 364.7
    acceleration: 81.13
    handling: 73.73
    nitro: 73.93
    average: 148.37
statMin:
    speed: 351.0
    acceleration: 73.9
    handling: 40.83
    nitro: 42.62
    average: 127.09
upgrade:
    speed: 7
    acceleration: 7
    handling: 7
    nitro: 7
    common: 16
    rare: 4
    epic: 0
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: Lamborghini
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
