id: 139
stars: 6
gameUpdate: 20
carOrder: 45
statOrder: 26
level: 10
epic: 4
model: SC20
slug: lamborghini-sc20
blueprint:
    star1: '0'
    star2: 28
    star3: 32
    star4: 44
    star5: 47
    star6: 0
    total: 151
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2907
    star1: 3095
    star2: 3316
    star3: 3519
    star4: 3779
    star5: 4043
    star6: 4307
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 370.7
    acceleration: 81.9
    handling: 72.51
    nitro: 68.9
    average: 148.5
statMin:
    speed: 353.4
    acceleration: 73.63
    handling: 51.04
    nitro: 40.77
    average: 129.71
upgrade:
    speed: 6
    acceleration: 6
    handling: 6
    nitro: 6
    common: 16
    rare: 4
    epic: 0
settingBlueprint:
    star1: Key
    star2: 28
    star3: 32
    star4: 44
    star5: 59
    star6: 86
    total: 249
settingBrand:
    name: Lamborghini
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
