id: 315
stars: 5
gameUpdate: 47
carOrder: 72
statOrder: 99
level: 0
epic: 0
model: 'BMW M4 GT3 EVO'
slug: lego-technic-bmw-m4-gt3-evo
blueprint:
    star1: ''
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 0
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 1
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2487
    star1: 2677
    star2: 0
    star3: 0
    star4: 0
    star5: 3896
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 333.5
    acceleration: 80.79
    handling: 82.01
    nitro: 74.7
    average: 142.75
statMin:
    speed: 320.0
    acceleration: 69.4
    handling: 56.88
    nitro: 55.2
    average: 125.37
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '99'
    star2: 99
    star3: 99
    star4: 99
    star5: 99
    star6: 99
    total: 594
settingBrand:
    name: 'Lego Technic'
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 99
    common: 99
    rare: 99
    epic: 99
settingUnitPrice:
    level01: 99999
    level02: 99999
    level03: 99999
    level04: 99999
    level05: 99999
    level06: 99999
    level07: 99999
    level08: 99999
    level09: 99999
    level10: 999999
    level11: 999999
    level12: 999999
    level13: 999999
    common: 99999
    rare: 999999
    epic: 999999
