id: 296
stars: 5
gameUpdate: 44
carOrder: 8
statOrder: 56
level: 6
epic: 0
model: 'Ferrari FXX K'
slug: lego-technic-ferrari-fxx-k
blueprint:
    star1: '30'
    star2: 35
    star3: 6
    star4: 0
    star5: 0
    star6: 0
    total: 71
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2382
    star1: 2511
    star2: 2690
    star3: 0
    star4: 0
    star5: 3522
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 364.5
    acceleration: 81.72
    handling: 45.97
    nitro: 64.46
    average: 139.16
statMin:
    speed: 350.0
    acceleration: 76.6
    handling: 38.45
    nitro: 50.68
    average: 128.93
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 35
    star3: 40
    star4: 45
    star5: 55
    star6: 0
    total: 205
settingBrand:
    name: 'Lego Technic'
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 12
    common: 28
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9550
    level02: 15600
    level03: 24900
    level04: 37400
    level05: 54000
    level06: 75500
    level07: 105000
    level08: 148000
    level09: 207500
    level10: 290000
    level11: 406000
    level12: 569000
    level13: null
    common: 60000
    rare: 120000
    epic: 360000
