id: 295
stars: 6
gameUpdate: 44
carOrder: 63
statOrder: 36
level: 8
epic: 0
model: 'Lamborghini Revuelto'
slug: lego-technic-lamborghini-revuelto
blueprint:
    star1: '25'
    star2: 30
    star3: 35
    star4: 0
    star5: 0
    star6: 0
    total: 90
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 2184
    star1: 2440
    star2: 2738
    star3: 0
    star4: 0
    star5: 0
    star6: 4264
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 368.2
    acceleration: 83.11
    handling: 64.07
    nitro: 50.97
    average: 141.59
statMin:
    speed: 350.0
    acceleration: 76.6
    handling: 43.03
    nitro: 13.98
    average: 120.9
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '25'
    star2: 30
    star3: 35
    star4: 40
    star5: 50
    star6: 60
    total: 240
settingBrand:
    name: 'Lego Technic'
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 13
    common: 32
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9890
    level02: 16100
    level03: 25800
    level04: 38700
    level05: 55900
    level06: 78500
    level07: 109500
    level08: 153500
    level09: 214500
    level10: 300500
    level11: 421000
    level12: 589000
    level13: 967500
    common: 70000
    rare: 140000
    epic: 420000
