id: 142
stars: 3
gameUpdate: 21
carOrder: 14
statOrder: 46
level: 10
epic: 3
model: 'McLaren Senna GTR'
slug: lego-technic-mclaren-senna-gtr
blueprint:
    star1: '0'
    star2: 28
    star3: 32
    star4: 44
    star5: 3
    star6: 0
    total: 107
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2594
    star1: 2736
    star2: 2932
    star3: 3171
    star4: 3491
    star5: 3846
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 349.8
    acceleration: 82.43
    handling: 79.32
    nitro: 65.28
    average: 144.21
statMin:
    speed: 335.0
    acceleration: 74.8
    handling: 57.64
    nitro: 49.12
    average: 129.14
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 28
    star3: 32
    star4: 44
    star5: 83
    star6: 0
    total: 187
settingBrand:
    name: 'Lego Technic'
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 12
    common: 24
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9550
    level02: 15600
    level03: 24900
    level04: 37400
    level05: 54000
    level06: 75500
    level07: 105000
    level08: 148000
    level09: 207500
    level10: 290000
    level11: 406000
    level12: 569000
    level13: null
    common: 60000
    rare: 120000
    epic: 360000
