id: 316
stars: 5
gameUpdate: 47
carOrder: 58
statOrder: 99
level: 3
epic: 0
model: 'LFA Nürburgring Package'
slug: lexus-lfa-nurburgring-package
blueprint:
    star1: '20'
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 20
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 4
    division: 9
rank:
    star0: 2106
    star1: 2294
    star2: 0
    star3: 0
    star4: 0
    star5: 3612
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 337.3
    acceleration: 74.12
    handling: 61.05
    nitro: 62.13
    average: 133.65
statMin:
    speed: 325.0
    acceleration: 67.6
    handling: 43.0
    nitro: 30.67
    average: 116.57
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '20'
    star2: 25
    star3: 30
    star4: 35
    star5: 40
    star6: 0
    total: 150
settingBrand:
    name: Lexus
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 99
    common: 99
    rare: 99
    epic: 99
settingUnitPrice:
    level01: 99999
    level02: 99999
    level03: 99999
    level04: 99999
    level05: 99999
    level06: 99999
    level07: 99999
    level08: 99999
    level09: 99999
    level10: 999999
    level11: 999999
    level12: 999999
    level13: 999999
    common: 99999
    rare: 999999
    epic: 999999
