id: 33
stars: 3
gameUpdate: 0
carOrder: 5
statOrder: 52
level: 10
epic: 4
model: 'Evora Sport 410'
slug: lotus-evora-sport-410
blueprint:
    star1: '20'
    star2: 20
    star3: 50
    star4: 0
    star5: 0
    star6: 0
    total: 90
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 1086
    star1: 1409
    star2: 1814
    star3: 2123
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 317.7
    acceleration: 71.7
    handling: 50.93
    nitro: 47.05
    average: 121.85
statMin:
    speed: 300.0
    acceleration: 62.2
    handling: 44.09
    nitro: 36.32
    average: 110.65
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 16
    rare: 4
    epic: 4
settingBlueprint:
    star1: '20'
    star2: 20
    star3: 50
    star4: 0
    star5: 0
    star6: 0
    total: 90
settingBrand:
    name: Lotus
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 10
    common: 16
    rare: 4
    epic: 4
settingUnitPrice:
    level01: 1500
    level02: 2400
    level03: 3900
    level04: 5900
    level05: 8500
    level06: 12000
    level07: 16500
    level08: 23000
    level09: 32500
    level10: 45500
    level11: null
    level12: null
    level13: null
    common: 10000
    rare: 20000
    epic: 60000
