id: 51
stars: 4
gameUpdate: 1
carOrder: 17
statOrder: 2
level: 11
epic: 4
model: 'Elise Sprint 220'
slug: lotus-elise-sprint-220
blueprint:
    star1: '10'
    star2: 12
    star3: 18
    star4: 28
    star5: 0
    star6: 0
    total: 68
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 3
    handling: 1
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 587
    star1: 1004
    star2: 1468
    star3: 1942
    star4: 2390
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 270.0
    acceleration: 82.25
    handling: 83.47
    nitro: 72.71
    average: 127.11
statMin:
    speed: 234.0
    acceleration: 59.5
    handling: 54.8
    nitro: 47.82
    average: 99.03
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 28
    rare: 8
    epic: 4
settingBlueprint:
    star1: '10'
    star2: 12
    star3: 18
    star4: 28
    star5: 0
    star6: 0
    total: 68
settingBrand:
    name: Lotus
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 2190
    level02: 3600
    level03: 5700
    level04: 8600
    level05: 12400
    level06: 17500
    level07: 24000
    level08: 34000
    level09: 47500
    level10: 66500
    level11: 93000
    level12: null
    level13: null
    common: 10000
    rare: 20000
    epic: 60000
