id: 207
stars: 5
gameUpdate: 30
carOrder: 36
statOrder: 38
level: 10
epic: 2
model: MC12
slug: maserati-mc12
blueprint:
    star1: '0'
    star2: 25
    star3: 32
    star4: 36
    star5: 34
    star6: 0
    total: 127
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 2
    nitro: 9
    mark: 5
    division: 9
rank:
    star0: 2141
    star1: 2334
    star2: 2605
    star3: 2847
    star4: 3162
    star5: 3660
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 342.9
    acceleration: 76.48
    handling: 72.36
    nitro: 38.94
    average: 132.67
statMin:
    speed: 330.0
    acceleration: 66.7
    handling: 47.13
    nitro: 9.5
    average: 113.33
upgrade:
    speed: 8
    acceleration: 8
    handling: 8
    nitro: 8
    common: 26
    rare: 4
    epic: 0
settingBlueprint:
    star1: Key
    star2: 25
    star3: 32
    star4: 36
    star5: 41
    star6: 0
    total: 134
settingBrand:
    name: Maserati
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 12
    common: 36
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 7130
    level02: 11600
    level03: 18600
    level04: 27900
    level05: 40300
    level06: 56500
    level07: 79000
    level08: 110500
    level09: 155000
    level10: 216500
    level11: 303000
    level12: 425000
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
