id: 94
stars: 6
gameUpdate: 12
carOrder: 66
statOrder: 4
level: 13
epic: 12
model: 'F1 LM'
slug: mclaren-f1-lm
blueprint:
    star1: Key
    star2: 26
    star3: 34
    star4: 46
    star5: 61
    star6: 78
    total: 245
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 2319
    star1: 2563
    star2: 2846
    star3: 3133
    star4: 3526
    star5: 3982
    star6: 4309
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 377.6
    acceleration: 74.66
    handling: 66.1
    nitro: 73.12
    average: 147.87
statMin:
    speed: 362.0
    acceleration: 64.9
    handling: 50.37
    nitro: 51.94
    average: 132.3
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 32
    rare: 20
    epic: 12
settingBlueprint:
    star1: Key
    star2: 26
    star3: 34
    star4: 46
    star5: 61
    star6: 78
    total: 245
settingBrand:
    name: McLaren
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 13
    common: 32
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9890
    level02: 16100
    level03: 25800
    level04: 38700
    level05: 55900
    level06: 78500
    level07: 109500
    level08: 153500
    level09: 214500
    level10: 300500
    level11: 421000
    level12: 589000
    level13: 967500
    common: 70000
    rare: 140000
    epic: 420000
