id: 192
stars: 6
gameUpdate: 28
carOrder: 39
statOrder: 9
level: 13
epic: 7
model: '650S GT3'
slug: mclaren-650s-gt3
blueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 1
    nitro: 1
    mark: 1
    division: 9
rank:
    star0: 2988
    star1: 3156
    star2: 3355
    star3: 3541
    star4: 3792
    star5: 4040
    star6: 4279
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 357.0
    acceleration: 84.34
    handling: 85.82
    nitro: 78.22
    average: 151.35
statMin:
    speed: 340.0
    acceleration: 73.9
    handling: 59.38
    nitro: 57.63
    average: 132.73
upgrade:
    speed: 7
    acceleration: 7
    handling: 7
    nitro: 7
    common: 16
    rare: 4
    epic: 0
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: McLaren
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
