id: 70
stars: 6
gameUpdate: 7
carOrder: 18
statOrder: 37
level: 13
epic: 14
model: Senna
slug: mclaren-senna
blueprint:
    star1: '60'
    star2: 13
    star3: 16
    star4: 25
    star5: 38
    star6: 48
    total: 200
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 1
    nitro: 1
    mark: 1
    division: 9
rank:
    star0: 2855
    star1: 3058
    star2: 3297
    star3: 3552
    star4: 3812
    star5: 4112
    star6: 4406
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 358.3
    acceleration: 82.91
    handling: 101.81
    nitro: 78.25
    average: 155.32
statMin:
    speed: 335.0
    acceleration: 74.8
    handling: 73.57
    nitro: 53.07
    average: 134.11
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 28
    rare: 20
    epic: 14
settingBlueprint:
    star1: '60'
    star2: 13
    star3: 16
    star4: 25
    star5: 38
    star6: 48
    total: 200
settingBrand:
    name: McLaren
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
