id: 224
stars: 4
gameUpdate: 33
carOrder: 18
statOrder: 57
level: 11
epic: 6
model: Artura
slug: mclaren-artura
blueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 2
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 2021
    star1: 2251
    star2: 2608
    star3: 2957
    star4: 3267
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 337.7
    acceleration: 81.05
    handling: 68.33
    nitro: 47.34
    average: 133.61
statMin:
    speed: 330.0
    acceleration: 73.0
    handling: 50.79
    nitro: 29.05
    average: 120.71
upgrade:
    speed: 6
    acceleration: 6
    handling: 6
    nitro: 6
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
settingBrand:
    name: McLaren
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 5750
    level02: 9400
    level03: 15000
    level04: 22500
    level05: 32500
    level06: 45500
    level07: 63500
    level08: 89000
    level09: 125000
    level10: 175000
    level11: 245000
    level12: null
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
