id: 54
stars: 6
gameUpdate: 2
carOrder: 27
statOrder: 34
level: 13
epic: 16
model: '570S Spider'
slug: mclaren-570s-spider
blueprint:
    star1: '50'
    star2: 12
    star3: 15
    star4: 24
    star5: 37
    star6: 45
    total: 183
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 2319
    star1: 2560
    star2: 2841
    star3: 3100
    star4: 3437
    star5: 3779
    star6: 4116
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 377.2
    acceleration: 79.23
    handling: 66.06
    nitro: 64.75
    average: 146.81
statMin:
    speed: 356.0
    acceleration: 71.2
    handling: 46.08
    nitro: 47.38
    average: 130.17
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 24
    rare: 20
    epic: 16
settingBlueprint:
    star1: '50'
    star2: 12
    star3: 15
    star4: 24
    star5: 37
    star6: 45
    total: 183
settingBrand:
    name: McLaren
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
