id: 310
stars: 5
gameUpdate: 46
carOrder: 71
statOrder: 99
level: 6
epic: 1
model: '750S Coupé'
slug: mclaren-750s-coupe
blueprint:
    star1: '25'
    star2: 30
    star3: 13
    star4: 0
    star5: 0
    star6: 0
    total: 68
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 2
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2564
    star1: 2762
    star2: 0
    star3: 0
    star4: 0
    star5: 3996
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 348.8
    acceleration: 83.02
    handling: 65.3
    nitro: 67.36
    average: 141.12
statMin:
    speed: 332.0
    acceleration: 75.7
    handling: 51.01
    nitro: 50.76
    average: 127.37
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '25'
    star2: 30
    star3: 35
    star4: 40
    star5: 50
    star6: 0
    total: 180
settingBrand:
    name: McLaren
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 36
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
