id: 105
stars: 6
gameUpdate: 14
carOrder: 29
statOrder: 27
level: 13
epic: 16
model: Speedtail
slug: mclaren-speedtail
blueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3402
    star1: 3559
    star2: 3741
    star3: 3937
    star4: 4138
    star5: 4372
    star6: 4593
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 416.7
    acceleration: 81.11
    handling: 56.65
    nitro: 74.2
    average: 157.17
statMin:
    speed: 403.0
    acceleration: 73.0
    handling: 46.04
    nitro: 53.96
    average: 144.0
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 26
    rare: 16
    epic: 4
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: McLaren
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
