id: 248
stars: 5
gameUpdate: 37
carOrder: 12
statOrder: 52
level: 10
epic: 6
model: Spéirling
slug: mcmurtry-speirling
blueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 13
    star6: 0
    total: 149
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 1
    nitro: 2
    mark: 1
    division: 9
rank:
    star0: 2603
    star1: 2741
    star2: 2930
    star3: 3151
    star4: 3460
    star5: 3789
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 331.7
    acceleration: 90.52
    handling: 80.62
    nitro: 61.7
    average: 141.14
statMin:
    speed: 320.0
    acceleration: 86.5
    handling: 49.7
    nitro: 37.03
    average: 123.31
upgrade:
    speed: 7
    acceleration: 7
    handling: 7
    nitro: 7
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 51
    star6: 0
    total: 187
settingBrand:
    name: McMurtry
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 12
    common: 24
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9550
    level02: 15600
    level03: 24900
    level04: 37400
    level05: 54000
    level06: 75500
    level07: 105000
    level08: 148000
    level09: 207500
    level10: 290000
    level11: 406000
    level12: 569000
    level13: null
    common: 60000
    rare: 120000
    epic: 360000
