id: 297
stars: 6
gameUpdate: 44
carOrder: 63
statOrder: 8
level: 3
epic: 0
model: 'Silver Lightning'
slug: mercedes-benz-silver-lightning
blueprint:
    star1: '30'
    star2: 29
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 59
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3311
    star1: 3485
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 4614
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 392.6
    acceleration: 83.03
    handling: 76.07
    nitro: 54.32
    average: 151.51
statMin:
    speed: 380.0
    acceleration: 76.6
    handling: 54.63
    nitro: 27.83
    average: 134.77
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 35
    star3: 40
    star4: 45
    star5: 55
    star6: 65
    total: 270
settingBrand:
    name: Mercedes-Benz
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
