id: 262
stars: 6
gameUpdate: 39
carOrder: 61
statOrder: 1
level: 13
epic: 16
model: 'Vision One-Eleven'
slug: mercedes-benz-vision-one-eleven
blueprint:
    star1: Key
    star2: 30
    star3: 40
    star4: 50
    star5: 65
    star6: 80
    total: 265
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 1
    nitro: 1
    mark: 1
    division: 9
rank:
    star0: 3299
    star1: 3471
    star2: 3676
    star3: 3865
    star4: 4111
    star5: 4358
    star6: 4600
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 384.3
    acceleration: 83.93
    handling: 81.26
    nitro: 81.68
    average: 157.79
statMin:
    speed: 364.5
    acceleration: 77.5
    handling: 50.62
    nitro: 52.2
    average: 136.21
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 24
    rare: 20
    epic: 16
settingBlueprint:
    star1: Key
    star2: 30
    star3: 40
    star4: 50
    star5: 65
    star6: 80
    total: 265
settingBrand:
    name: Mercedes-Benz
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
