id: 231
stars: 4
gameUpdate: 34
carOrder: 25
statOrder: 43
level: 11
epic: 4
model: '2022 Showcar Vision AMG'
slug: mercedes-benz-2022-showcar-vision-amg
blueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 1889
    star1: 2185
    star2: 2576
    star3: 2962
    star4: 3294
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 335.1
    acceleration: 75.36
    handling: 51.75
    nitro: 59.32
    average: 130.38
statMin:
    speed: 321.0
    acceleration: 64.9
    handling: 34.71
    nitro: 26.57
    average: 111.79
upgrade:
    speed: 9
    acceleration: 9
    handling: 8
    nitro: 8
    common: 22
    rare: 7
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
settingBrand:
    name: Mercedes-Benz
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 12
    epic: 4
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
