id: 123
stars: 4
gameUpdate: 17
carOrder: 3
statOrder: 58
level: 11
epic: 3
model: EP9
slug: nio-ep9
blueprint:
    star1: '60'
    star2: 40
    star3: 51
    star4: 63
    star5: 0
    star6: 0
    total: 214
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 2
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2113
    star1: 2359
    star2: 2619
    star3: 2910
    star4: 3194
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 326.1
    acceleration: 83.03
    handling: 70.49
    nitro: 68.68
    average: 137.08
statMin:
    speed: 313.0
    acceleration: 75.7
    handling: 52.47
    nitro: 49.64
    average: 122.7
upgrade:
    speed: 7
    acceleration: 7
    handling: 6
    nitro: 6
    common: 19
    rare: 2
    epic: 0
settingBlueprint:
    star1: '60'
    star2: 40
    star3: 51
    star4: 63
    star5: 0
    star6: 0
    total: 214
settingBrand:
    name: Nio
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 11
    common: 20
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 6440
    level02: 10500
    level03: 16800
    level04: 25200
    level05: 36400
    level06: 51000
    level07: 71500
    level08: 100000
    level09: 140000
    level10: 196000
    level11: 274000
    level12: 384000
    level13: null
    common: 15000
    rare: 30000
    epic: 90000
