id: 217
stars: 4
gameUpdate: 32
carOrder: 28
statOrder: 7
level: 11
epic: 0
model: '370Z Édition Néon'
slug: nissan-370z-edition-neon
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 2
    handling: 1
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 570
    star1: 1030
    star2: 1576
    star3: 2138
    star4: 2675
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 271.1
    acceleration: 83.26
    handling: 82.81
    nitro: 65.22
    average: 125.6
statMin:
    speed: 250.0
    acceleration: 53.2
    handling: 49.95
    nitro: 35.38
    average: 97.13
upgrade:
    speed: 4
    acceleration: 4
    handling: 4
    nitro: 4
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Nissan
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
