id: 249
stars: 6
gameUpdate: 37
carOrder: 15
statOrder: 56
level: 10
epic: 5
model: 'GT-R Néon Édition'
slug: nissan-gt-r-neon-edition
blueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 30
    star6: 0
    total: 207
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 1
    handling: 1
    nitro: 2
    mark: 1
    division: 9
rank:
    star0: 2487
    star1: 2736
    star2: 3028
    star3: 3340
    star4: 3659
    star5: 4026
    star6: 4382
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 361.4
    acceleration: 87.55
    handling: 89.35
    nitro: 67.55
    average: 151.46
statMin:
    speed: 333.5
    acceleration: 76.6
    handling: 47.48
    nitro: 35.17
    average: 123.19
upgrade:
    speed: 5
    acceleration: 5
    handling: 5
    nitro: 5
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Nissan
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
