id: 39
stars: 6
gameUpdate: 0
carOrder: 38
statOrder: 24
level: 13
epic: 16
model: 'Huayra BC'
slug: pagani-huayra-bc
blueprint:
    star1: '50'
    star2: 12
    star3: 15
    star4: 24
    star5: 37
    star6: 45
    total: 183
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 2
    nitro: 1
    mark: 2
    division: 9
rank:
    star0: 2983
    star1: 3158
    star2: 3362
    star3: 3548
    star4: 3795
    star5: 4041
    star6: 4274
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 365.4
    acceleration: 80.04
    handling: 63.11
    nitro: 86.75
    average: 148.83
statMin:
    speed: 350.0
    acceleration: 71.2
    handling: 46.1
    nitro: 73.11
    average: 135.1
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 24
    rare: 20
    epic: 16
settingBlueprint:
    star1: '50'
    star2: 12
    star3: 15
    star4: 24
    star5: 37
    star6: 45
    total: 183
settingBrand:
    name: Pagani
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 5290
    level02: 8600
    level03: 13800
    level04: 20700
    level05: 29900
    level06: 42000
    level07: 58500
    level08: 82000
    level09: 115000
    level10: 161000
    level11: 225000
    level12: 315000
    level13: 517000
    common: 35000
    rare: 70000
    epic: 210000
