id: 180
stars: 6
gameUpdate: 26
carOrder: 69
statOrder: 12
level: 13
epic: 2
model: 'Huayra R'
slug: pagani-huayra-r
blueprint:
    star1: '55'
    star2: 18
    star3: 24
    star4: 32
    star5: 47
    star6: 50
    total: 226
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2356
    star1: 2600
    star2: 2883
    star3: 3173
    star4: 3566
    star5: 4030
    star6: 4363
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 376.6
    acceleration: 83.17
    handling: 58.41
    nitro: 64.38
    average: 145.64
statMin:
    speed: 360.0
    acceleration: 73.0
    handling: 42.36
    nitro: 43.41
    average: 129.69
upgrade:
    speed: 6
    acceleration: 6
    handling: 6
    nitro: 6
    common: 10
    rare: 0
    epic: 0
settingBlueprint:
    star1: '55'
    star2: 18
    star3: 24
    star4: 32
    star5: 47
    star6: 50
    total: 226
settingBrand:
    name: Pagani
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 13
    common: 32
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9890
    level02: 16100
    level03: 25800
    level04: 38700
    level05: 55900
    level06: 78500
    level07: 109500
    level08: 153500
    level09: 214500
    level10: 300500
    level11: 421000
    level12: 589000
    level13: 967500
    common: 70000
    rare: 140000
    epic: 420000
