id: 193
stars: 6
gameUpdate: 28
carOrder: 25
statOrder: 15
level: 13
epic: 16
model: 9X8
slug: peugeot-9x8
blueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 1
    nitro: 2
    mark: 1
    division: 9
rank:
    star0: 2794
    star1: 2968
    star2: 3175
    star3: 3366
    star4: 3615
    star5: 3867
    star6: 4108
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 344.3
    acceleration: 90.03
    handling: 94.15
    nitro: 69.94
    average: 149.61
statMin:
    speed: 330.0
    acceleration: 82.0
    handling: 61.79
    nitro: 48.59
    average: 130.6
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 24
    rare: 20
    epic: 16
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: Peugeot
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
