id: 118
stars: 6
gameUpdate: 16
carOrder: 30
statOrder: 20
level: 12
epic: 5
model: Onyx
slug: peugeot-onyx
blueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 49
    total: 237
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 1
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 2855
    star1: 3026
    star2: 3226
    star3: 3413
    star4: 3739
    star5: 3917
    star6: 4145
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 370.6
    acceleration: 81.93
    handling: 84.82
    nitro: 59.61
    average: 149.24
statMin:
    speed: 360.0
    acceleration: 73.9
    handling: 63.83
    nitro: 35.08
    average: 133.2
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 20
    rare: 18
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 62
    total: 250
settingBrand:
    name: Peugeot
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
