id: 40
stars: 4
gameUpdate: 0
carOrder: 16
statOrder: 37
level: 11
epic: 4
model: 'H2 Speed'
slug: pininfarina-h2-speed
blueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 32
    star5: 0
    star6: 0
    total: 103
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 2
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 1685
    star1: 1969
    star2: 2332
    star3: 2695
    star4: 3003
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 316.3
    acceleration: 85.72
    handling: 57.94
    nitro: 71.91
    average: 132.97
statMin:
    speed: 300.0
    acceleration: 69.4
    handling: 64.66
    nitro: 41.8
    average: 118.96
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 24
    rare: 12
    epic: 4
settingBlueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 32
    star5: 0
    star6: 0
    total: 103
settingBrand:
    name: Pininfarina
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 12
    epic: 4
settingUnitPrice:
    level01: 2530
    level02: 4100
    level03: 6600
    level04: 9900
    level05: 14300
    level06: 20000
    level07: 28000
    level08: 39000
    level09: 55000
    level10: 77000
    level11: 108000
    level12: null
    level13: null
    common: 15000
    rare: 30000
    epic: 90000
