id: 194
stars: 3
gameUpdate: 28
carOrder: 3
statOrder: 55
level: 10
epic: 2
model: 'Boxster 25th Anniversary'
slug: porsche-boxster-25th-anniversary
blueprint:
    star1: '55'
    star2: 38
    star3: 90
    star4: 0
    star5: 0
    star6: 0
    total: 183
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 9
    handling: 3
    nitro: 3
    mark: 6
    division: 9
rank:
    star0: 920
    star1: 1210
    star2: 1571
    star3: 1844
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 298.4
    acceleration: 71.92
    handling: 45.93
    nitro: 53.86
    average: 117.53
statMin:
    speed: 288.0
    acceleration: 64.0
    handling: 39.54
    nitro: 35.31
    average: 106.71
upgrade:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '55'
    star2: 38
    star3: 90
    star4: 0
    star5: 0
    star6: 0
    total: 183
settingBrand:
    name: Porsche
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 10
    common: 16
    rare: 4
    epic: 4
settingUnitPrice:
    level01: 1500
    level02: 2400
    level03: 3900
    level04: 5900
    level05: 8500
    level06: 12000
    level07: 16500
    level08: 23000
    level09: 32500
    level10: 45500
    level11: null
    level12: null
    level13: null
    common: 10000
    rare: 20000
    epic: 60000
