id: 243
stars: 4
gameUpdate: 36
carOrder: 14
statOrder: 36
level: 9
epic: 1
model: '911 Carrera RS 3.8'
slug: porsche-911-carrera-rs-3-8
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 16
    star5: 0
    star6: 0
    total: 102
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 9
    handling: 2
    nitro: 9
    mark: 7
    division: 9
rank:
    star0: 599
    star1: 991
    star2: 1438
    star3: 1896
    star4: 2339
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 296.9
    acceleration: 70.52
    handling: 65.24
    nitro: 35.55
    average: 117.05
statMin:
    speed: 270.0
    acceleration: 55.9
    handling: 39.13
    nitro: 11.68
    average: 94.18
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Porsche
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
