id: 41
stars: 3
gameUpdate: 0
carOrder: 1
statOrder: 71
level: 10
epic: 4
model: '911 GTS Coupé'
slug: porsche-911-gts-coupe
blueprint:
    star1: '30'
    star2: 30
    star3: 70
    star4: 0
    star5: 0
    star6: 0
    total: 130
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 1243
    star1: 1560
    star2: 1898
    star3: 2186
    star4: 0
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 328.8
    acceleration: 71.21
    handling: 45.85
    nitro: 56.6
    average: 125.62
statMin:
    speed: 312.0
    acceleration: 64.9
    handling: 41.08
    nitro: 42.95
    average: 115.23
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 24
    rare: 4
    epic: 4
settingBlueprint:
    star1: '30'
    star2: 30
    star3: 70
    star4: 0
    star5: 0
    star6: 0
    total: 130
settingBrand:
    name: Porsche
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 10
    common: 24
    rare: 4
    epic: 4
settingUnitPrice:
    level01: 1840
    level02: 3000
    level03: 4800
    level04: 7200
    level05: 10400
    level06: 14500
    level07: 20500
    level08: 28500
    level09: 40000
    level10: 56000
    level11: null
    level12: null
    level13: null
    common: 15000
    rare: 30000
    epic: 90000
