id: 213
stars: 5
gameUpdate: 31
carOrder: 50
statOrder: 11
level: 12
epic: 2
model: 'Panamera Turbo S'
slug: porsche-panamera-turbo-s
blueprint:
    star1: Key
    star2: 25
    star3: 32
    star4: 36
    star5: 41
    star6: 0
    total: 134
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 2
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 2283
    star1: 2495
    star2: 2798
    star3: 3066
    star4: 3405
    star5: 3971
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 326.3
    acceleration: 88.03
    handling: 72.48
    nitro: 58.56
    average: 136.34
statMin:
    speed: 315.0
    acceleration: 81.1
    handling: 38.51
    nitro: 26.22
    average: 115.21
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 33
    rare: 12
    epic: 0
settingBlueprint:
    star1: Key
    star2: 25
    star3: 32
    star4: 36
    star5: 41
    star6: 0
    total: 134
settingBrand:
    name: Porsche
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 12
    common: 36
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 7130
    level02: 11600
    level03: 18600
    level04: 27900
    level05: 40300
    level06: 56500
    level07: 79000
    level08: 110500
    level09: 155000
    level10: 216500
    level11: 303000
    level12: 425000
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
