id: 277
stars: 4
gameUpdate: 41
carOrder: 22
statOrder: 7
level: 4
epic: 1
model: '911 50 Years Porsche Design'
slug: porsche-911-50-years-porsche-design
blueprint:
    star1: '35'
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 35
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 1
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 1832
    star1: 2126
    star2: 2515
    star3: 2897
    star4: 3210
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 312.6
    acceleration: 79.72
    handling: 84.61
    nitro: 70.45
    average: 136.85
statMin:
    speed: 300.0
    acceleration: 68.5
    handling: 57.8
    nitro: 47.29
    average: 118.4
upgrade:
    speed: 4
    acceleration: 4
    handling: 4
    nitro: 0
    common: 7
    rare: 0
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
settingBrand:
    name: Porsche
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 4
settingUnitPrice:
    level01: 5060
    level02: 8300
    level03: 13200
    level04: 19800
    level05: 28600
    level06: 40000
    level07: 56000
    level08: 78500
    level09: 110000
    level10: 154000
    level11: 215000
    level12: null
    level13: null
    common: 30000
    rare: 60000
    epic: 180000
