id: 66
stars: 4
gameUpdate: 6
carOrder: 23
statOrder: 34
level: 11
epic: 4
model: '911 Targa 4S'
slug: porsche-911-targa-4s
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 9
    mark: 6
    division: 9
rank:
    star0: 1063
    star1: 1397
    star2: 1790
    star3: 2192
    star4: 2589
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 315.1
    acceleration: 75.37
    handling: 41.57
    nitro: 38.35
    average: 117.6
statMin:
    speed: 303.0
    acceleration: 64.0
    handling: 29.2
    nitro: 18.15
    average: 103.59
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 28
    rare: 8
    epic: 4
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Porsche
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
