id: 256
stars: 3
gameUpdate: 38
carOrder: 24
statOrder: 41
level: 10
epic: 4
model: 'Mission R'
slug: porsche-mission-r
blueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 1
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 1817
    star1: 2117
    star2: 2513
    star3: 2905
    star4: 3229
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 312.1
    acceleration: 87.92
    handling: 63.47
    nitro: 62.72
    average: 131.55
statMin:
    speed: 300.0
    acceleration: 77.5
    handling: 37.23
    nitro: 38.14
    average: 113.22
upgrade:
    speed: 6
    acceleration: 6
    handling: 6
    nitro: 6
    common: 14
    rare: 0
    epic: 0
settingBlueprint:
    star1: '50'
    star2: 29
    star3: 38
    star4: 48
    star5: 0
    star6: 0
    total: 165
settingBrand:
    name: Porsche
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 11
    common: 24
    rare: 12
    epic: 4
settingUnitPrice:
    level01: 5060
    level02: 8300
    level03: 13200
    level04: 19800
    level05: 28600
    level06: 40000
    level07: 56000
    level08: 78500
    level09: 110000
    level10: 154000
    level11: 215000
    level12: null
    level13: null
    common: 30000
    rare: 60000
    epic: 180000
