id: 89
stars: 6
gameUpdate: 11
carOrder: 37
statOrder: 14
level: 13
epic: 16
model: '911 GT2 RS Clubsport'
slug: porsche-911-gt2-rs-clubsport
blueprint:
    star1: Key
    star2: 28
    star3: 32
    star4: 44
    star5: 59
    star6: 86
    total: 249
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 1
    nitro: 2
    mark: 1
    division: 9
rank:
    star0: 2702
    star1: 2914
    star2: 3160
    star3: 3387
    star4: 3680
    star5: 3977
    star6: 4270
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 356.9
    acceleration: 83.64
    handling: 85.42
    nitro: 73.65
    average: 149.9
statMin:
    speed: 340.0
    acceleration: 74.8
    handling: 55.63
    nitro: 49.64
    average: 130.02
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 24
    rare: 20
    epic: 16
settingBlueprint:
    star1: Key
    star2: 28
    star3: 32
    star4: 44
    star5: 59
    star6: 86
    total: 249
settingBrand:
    name: Porsche
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
