id: 71
stars: 6
gameUpdate: 7
carOrder: 61
statOrder: 1
level: 13
epic: 12
model: '911 GT3 RS'
slug: porsche-911-gt3-rs
blueprint:
    star1: '55'
    star2: 18
    star3: 24
    star4: 32
    star5: 47
    star6: 50
    total: 226
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 2
    handling: 1
    nitro: 1
    mark: 1
    division: 9
rank:
    star0: 1809
    star1: 2109
    star2: 2458
    star3: 2806
    star4: 3285
    star5: 3824
    star6: 4211
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 339.4
    acceleration: 85.84
    handling: 92.97
    nitro: 86.39
    average: 151.15
statMin:
    speed: 312.0
    acceleration: 71.2
    handling: 52.35
    nitro: 52.35
    average: 121.98
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 32
    rare: 20
    epic: 12
settingBlueprint:
    star1: '55'
    star2: 18
    star3: 24
    star4: 32
    star5: 47
    star6: 50
    total: 226
settingBrand:
    name: Porsche
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 13
    common: 32
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9890
    level02: 16100
    level03: 25800
    level04: 38700
    level05: 55900
    level06: 78500
    level07: 109500
    level08: 153500
    level09: 214500
    level10: 300500
    level11: 421000
    level12: 589000
    level13: 967500
    common: 70000
    rare: 140000
    epic: 420000
