id: 271
stars: 4
gameUpdate: 40
carOrder: 23
statOrder: 52
level: 4
epic: 2
model: '911 Turbo 50 Years'
slug: porsche-911-turbo-50-years
blueprint:
    star1: '55'
    star2: 17
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 72
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 3
    nitro: 3
    mark: 3
    division: 9
rank:
    star0: 2193
    star1: 2432
    star2: 2805
    star3: 3172
    star4: 3495
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 343.5
    acceleration: 82.94
    handling: 53.72
    nitro: 59.39
    average: 134.89
statMin:
    speed: 330.0
    acceleration: 75.7
    handling: 32.47
    nitro: 34.91
    average: 118.27
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '55'
    star2: 35
    star3: 44
    star4: 54
    star5: 0
    star6: 0
    total: 188
settingBrand:
    name: Porsche
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 11
    common: 24
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 5750
    level02: 9400
    level03: 15000
    level04: 22500
    level05: 32500
    level06: 45500
    level07: 63500
    level08: 89000
    level09: 125000
    level10: 175000
    level11: 245000
    level12: null
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
