id: 318
stars: 6
gameUpdate: 47
carOrder: 64
statOrder: 99
level: 0
epic: 0
model: '935 Dragonforce Edition'
slug: porsche-935-dragonforce-edition
blueprint:
    star1: ''
    star2: 12
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 12
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 2
    nitro: 1
    mark: 3
    division: 9
rank:
    star0: 2996
    star1: 3171
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 4289
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 366.8
    acceleration: 79.23
    handling: 76.05
    nitro: 75.55
    average: 149.41
statMin:
    speed: 355.0
    acceleration: 71.2
    handling: 53.52
    nitro: 55.33
    average: 133.76
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 50
    star5: 60
    star6: 75
    total: 270
settingBrand:
    name: Porsche
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
