id: 278
stars: 5
gameUpdate: 41
carOrder: 31
statOrder: 10
level: 8
epic: 1
model: Bohema
slug: praga-bohema
blueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 9
    star5: 0
    star6: 0
    total: 80
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 3
    handling: 1
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2063
    star1: 2251
    star2: 2522
    star3: 2761
    star4: 3053
    star5: 3553
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 315.7
    acceleration: 80.72
    handling: 80.22
    nitro: 69.65
    average: 136.57
statMin:
    speed: 300.0
    acceleration: 68.5
    handling: 54.37
    nitro: 47.29
    average: 117.54
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '35'
    star2: 15
    star3: 21
    star4: 28
    star5: 35
    star6: 0
    total: 134
settingBrand:
    name: Praga
settingClass:
    value: C
    carsNumber: 58
    median: 139
settingLevel:
    level: 12
    common: 36
    rare: 16
    epic: 8
settingUnitPrice:
    level01: 7130
    level02: 11600
    level03: 18600
    level04: 27900
    level05: 40300
    level06: 56500
    level07: 79000
    level08: 110500
    level09: 155000
    level10: 216500
    level11: 303000
    level12: 425000
    level13: null
    common: 40000
    rare: 80000
    epic: 240000
