id: 195
stars: 4
gameUpdate: 28
carOrder: 25
statOrder: 18
level: 11
epic: 0
model: R1
slug: praga-r1
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 1
    handling: 2
    nitro: 2
    mark: 3
    division: 9
rank:
    star0: 1151
    star1: 1488
    star2: 1864
    star3: 2253
    star4: 2624
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 283.3
    acceleration: 87.8
    handling: 62.25
    nitro: 60.92
    average: 123.57
statMin:
    speed: 268.0
    acceleration: 74.8
    handling: 42.12
    nitro: 38.73
    average: 105.91
upgrade:
    speed: 7
    acceleration: 7
    handling: 7
    nitro: 7
    common: 20
    rare: 0
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Praga
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
