id: 161
stars: 5
gameUpdate: 23
carOrder: 51
statOrder: 8
level: 12
epic: 8
model: Berlinetta
slug: puritalia-berlinetta
blueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 2
    handling: 1
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2603
    star1: 2803
    star2: 3090
    star3: 3347
    star4: 3721
    star5: 4076
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 349.5
    acceleration: 83.43
    handling: 82.74
    nitro: 69.66
    average: 146.33
statMin:
    speed: 330.0
    acceleration: 75.7
    handling: 50.79
    nitro: 34.91
    average: 122.85
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 32
    rare: 20
    epic: 8
settingBlueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
settingBrand:
    name: Puritalia
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
