id: 144
stars: 6
gameUpdate: 21
carOrder: 6
statOrder: 67
level: 6
epic: 3
model: 'Tachyon Speed'
slug: raesr-tachyon-speed
blueprint:
    star1: '0'
    star2: 40
    star3: 24
    star4: 0
    star5: 0
    star6: 0
    total: 64
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 9
    handling: 3
    nitro: 3
    mark: 4
    division: 9
rank:
    star0: 3035
    star1: 3174
    star2: 3340
    star3: 3516
    star4: 3697
    star5: 3905
    star6: 4109
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 400.3
    acceleration: 77.91
    handling: 53.44
    nitro: 59.94
    average: 147.9
statMin:
    speed: 389.0
    acceleration: 73.45
    handling: 44.85
    nitro: 43.75
    average: 137.76
upgrade:
    speed: 4
    acceleration: 4
    handling: 3
    nitro: 3
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: Raesr
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
