id: 272
stars: 6
gameUpdate: 40
carOrder: 72
statOrder: 2
level: 0
epic: 0
model: Tartarus
slug: raesr-tartarus
blueprint:
    star1: '0'
    star2: 1
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 1
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 1
    handling: 2
    nitro: 9
    mark: 3
    division: 9
rank:
    star0: 4097
    star1: 4255
    star2: 4438
    star3: 4631
    star4: 4830
    star5: 5064
    star6: 5285
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 538.7
    acceleration: 90.64
    handling: 61.77
    nitro: 30.57
    average: 180.42
statMin:
    speed: 530.0
    acceleration: 87.4
    handling: 42.62
    nitro: 18.26
    average: 169.57
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: Raesr
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
