id: 145
stars: 4
gameUpdate: 21
carOrder: 27
statOrder: 16
level: 11
epic: 4
model: TreZor
slug: renault-trezor
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 5
    division: 9
rank:
    star0: 1212
    star1: 1541
    star2: 1914
    star3: 2296
    star4: 2667
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 294.5
    acceleration: 78.62
    handling: 61.93
    nitro: 61.07
    average: 124.03
statMin:
    speed: 280.0
    acceleration: 64.0
    handling: 42.06
    nitro: 41.62
    average: 106.92
upgrade:
    speed: 9
    acceleration: 9
    handling: 8
    nitro: 9
    common: 23
    rare: 1
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Renault
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
