id: 181
stars: 4
gameUpdate: 26
carOrder: 10
statOrder: 15
level: 11
epic: 4
model: Dezir
slug: renault-dezir
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 9
    acceleration: 9
    handling: 2
    nitro: 2
    mark: 5
    division: 9
rank:
    star0: 899
    star1: 1192
    star2: 1531
    star3: 1879
    star4: 2213
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 293.2
    acceleration: 65.56
    handling: 69.43
    nitro: 68.44
    average: 124.16
statMin:
    speed: 275.7
    acceleration: 55.0
    handling: 44.86
    nitro: 51.55
    average: 106.78
upgrade:
    speed: 7
    acceleration: 7
    handling: 7
    nitro: 7
    common: 20
    rare: 0
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: Renault
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
