id: 225
stars: 6
gameUpdate: 33
carOrder: 26
statOrder: 51
level: 6
epic: 3
model: 'Concept S'
slug: rimac-concept-s
blueprint:
    star1: '85'
    star2: 25
    star3: 5
    star4: 0
    star5: 0
    star6: 0
    total: 115
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3089
    star1: 3277
    star2: 3497
    star3: 3733
    star4: 3976
    star5: 4260
    star6: 4528
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 376.3
    acceleration: 84.53
    handling: 79.9
    nitro: 69.86
    average: 152.65
statMin:
    speed: 365.0
    acceleration: 78.85
    handling: 46.73
    nitro: 41.74
    average: 133.08
upgrade:
    speed: 3
    acceleration: 3
    handling: 3
    nitro: 3
    common: 4
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Rimac
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 32
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
