id: 146
stars: 6
gameUpdate: 21
carOrder: 52
statOrder: 28
level: 8
epic: 4
model: Concept_One
slug: rimac-concept-one
blueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 8
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 1
    handling: 1
    nitro: 3
    mark: 1
    division: 9
rank:
    star0: 3176
    star1: 3348
    star2: 3551
    star3: 3741
    star4: 3989
    star5: 4237
    star6: 4480
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 368.5
    acceleration: 86.34
    handling: 84.08
    nitro: 54.53
    average: 148.36
statMin:
    speed: 355.0
    acceleration: 77.5
    handling: 59.7
    nitro: 33.7
    average: 131.48
upgrade:
    speed: 4
    acceleration: 4
    handling: 4
    nitro: 5
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: '70'
    star2: 23
    star3: 27
    star4: 36
    star5: 52
    star6: 59
    total: 267
settingBrand:
    name: Rimac
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 24
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
