id: 219
stars: 6
gameUpdate: 32
carOrder: 32
statOrder: 18
level: 3
epic: 1
model: 'S7 Twin Turbo'
slug: saleen-s7-twin-turbo
blueprint:
    star1: '0'
    star2: 8
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 8
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 9
    handling: 2
    nitro: 1
    mark: 3
    division: 9
rank:
    star0: 3471
    star1: 3620
    star2: 3796
    star3: 3983
    star4: 4179
    star5: 4405
    star6: 4629
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 429.9
    acceleration: 69.5
    handling: 68.97
    nitro: 77.31
    average: 161.42
statMin:
    speed: 402.0
    acceleration: 62.2
    handling: 62.89
    nitro: 60.64
    average: 146.93
upgrade:
    speed: 3
    acceleration: 3
    handling: 3
    nitro: 3
    common: 12
    rare: 0
    epic: 0
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: Saleen
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
