id: 55
stars: 5
gameUpdate: 2
carOrder: 40
statOrder: 18
level: 12
epic: 8
model: 'R1 550'
slug: sin-r1-550
blueprint:
    star1: '30'
    star2: 9
    star3: 13
    star4: 21
    star5: 32
    star6: 0
    total: 105
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 3
    nitro: 1
    mark: 3
    division: 9
rank:
    star0: 2545
    star1: 2743
    star2: 3025
    star3: 3272
    star4: 3628
    star5: 3971
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 370.6
    acceleration: 77.04
    handling: 45.74
    nitro: 85.0
    average: 144.6
statMin:
    speed: 350.0
    acceleration: 68.5
    handling: 36.92
    nitro: 63.94
    average: 129.84
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 32
    rare: 20
    epic: 8
settingBlueprint:
    star1: '30'
    star2: 9
    star3: 13
    star4: 21
    star5: 32
    star6: 0
    total: 105
settingBrand:
    name: Sin
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 12
    common: 32
    rare: 20
    epic: 8
settingUnitPrice:
    level01: 7820
    level02: 12800
    level03: 20400
    level04: 30600
    level05: 44200
    level06: 62000
    level07: 86500
    level08: 121500
    level09: 170000
    level10: 237500
    level11: 333000
    level12: 466000
    level13: null
    common: 50000
    rare: 100000
    epic: 300000
