id: 199
stars: 6
gameUpdate: 29
carOrder: 14
statOrder: 65
level: 0
epic: 2
model: '2015 GTA Spano'
slug: spania-gta-2015-gta-spano
blueprint:
    star1: '57'
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 57
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3266
    star1: 3408
    star2: 3579
    star3: 3760
    star4: 3949
    star5: 4168
    star6: 4373
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 383.7
    acceleration: 81.2
    handling: 59.72
    nitro: 69.97
    average: 148.65
statMin:
    speed: 373.0
    acceleration: 73.9
    handling: 49.08
    nitro: 53.09
    average: 137.27
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: 'Spania GTA'
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
