id: 99
stars: 6
gameUpdate: 13
carOrder: 56
statOrder: 7
level: 13
epic: 16
model: Tuatara
slug: ssc-tuatara
blueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3758
    star1: 3918
    star2: 4105
    star3: 4303
    star4: 4506
    star5: 4744
    star6: 4969
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 490.6
    acceleration: 82.51
    handling: 48.77
    nitro: 62.04
    average: 170.98
statMin:
    speed: 482.8
    acceleration: 74.8
    handling: 42.34
    nitro: 38.72
    average: 159.67
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 28
    rare: 20
    epic: 16
settingBlueprint:
    star1: Key
    star2: 40
    star3: 45
    star4: 60
    star5: 70
    star6: 85
    total: 300
settingBrand:
    name: SSC
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
