id: 147
stars: 6
gameUpdate: 21
carOrder: 44
statOrder: 11
level: 0
epic: 1
model: 1MW
slug: toroidion-1mw
blueprint:
    star1: '6'
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 0
    total: 6
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 2
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3518
    star1: 3685
    star2: 3883
    star3: 4096
    star4: 4314
    star5: 4571
    star6: 4806
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 460.6
    acceleration: 81.29
    handling: 60.32
    nitro: 54.19
    average: 164.1
statMin:
    speed: 451.0
    acceleration: 74.8
    handling: 44.84
    nitro: 36.04
    average: 151.67
upgrade:
    speed: 0
    acceleration: 0
    handling: 0
    nitro: 0
    common: 0
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Toroidion
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
