id: 72
stars: 4
gameUpdate: 7
carOrder: 31
statOrder: 20
level: 11
epic: 4
model: Griffith
slug: tvr-griffith
blueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
evo:
    number: 0
gauntlet:
    speed: 3
    acceleration: 9
    handling: 3
    nitro: 9
    mark: 6
    division: 9
rank:
    star0: 1307
    star1: 1630
    star2: 2001
    star3: 2381
    star4: 2751
    star5: 0
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 338.7
    acceleration: 69.28
    handling: 47.31
    nitro: 37.49
    average: 123.2
statMin:
    speed: 322.0
    acceleration: 64.0
    handling: 39.11
    nitro: 17.02
    average: 110.53
upgrade:
    speed: 11
    acceleration: 11
    handling: 11
    nitro: 11
    common: 28
    rare: 8
    epic: 4
settingBlueprint:
    star1: '30'
    star2: 23
    star3: 33
    star4: 42
    star5: 0
    star6: 0
    total: 128
settingBrand:
    name: TVR
settingClass:
    value: D
    carsNumber: 43
    median: 125
settingLevel:
    level: 11
    common: 28
    rare: 8
    epic: 4
settingUnitPrice:
    level01: 4370
    level02: 7100
    level03: 11400
    level04: 17100
    level05: 24700
    level06: 34500
    level07: 48500
    level08: 68000
    level09: 95000
    level10: 133000
    level11: 186000
    level12: null
    level13: null
    common: 20000
    rare: 40000
    epic: 120000
