id: 163
stars: 6
gameUpdate: 23
carOrder: 21
statOrder: 59
level: 13
epic: 16
model: '1789'
slug: vision-1789
blueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3232
    star1: 3390
    star2: 3576
    star3: 3773
    star4: 3974
    star5: 4212
    star6: 4435
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 390.2
    acceleration: 81.29
    handling: 59.91
    nitro: 72.19
    average: 150.9
statMin:
    speed: 380.0
    acceleration: 74.8
    handling: 44.08
    nitro: 47.32
    average: 136.55
upgrade:
    speed: 10
    acceleration: 10
    handling: 10
    nitro: 10
    common: 19
    rare: 0
    epic: 0
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Vision
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
