id: 46
stars: 5
gameUpdate: 0
carOrder: 18
statOrder: 42
level: 12
epic: 12
model: 'Force 1 V10'
slug: vlf-force-1-v10
blueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 3
    handling: 3
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 2706
    star1: 2846
    star2: 3038
    star3: 3272
    star4: 3587
    star5: 3929
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 368.8
    acceleration: 80.33
    handling: 54.68
    nitro: 74.62
    average: 144.61
statMin:
    speed: 350.0
    acceleration: 73.9
    handling: 43.04
    nitro: 60.87
    average: 131.95
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 24
    rare: 20
    epic: 12
settingBlueprint:
    star1: '45'
    star2: 17
    star3: 23
    star4: 32
    star5: 45
    star6: 0
    total: 162
settingBrand:
    name: VLF
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 12
    common: 24
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 4260
    level02: 6900
    level03: 11100
    level04: 16700
    level05: 24100
    level06: 33500
    level07: 47000
    level08: 66000
    level09: 92500
    level10: 129000
    level11: 181000
    level12: 254000
    level13: null
    common: 30000
    rare: 60000
    epic: 180000
