id: 133
stars: 6
gameUpdate: 19
carOrder: 68
statOrder: 5
level: 13
epic: 12
model: 'W12 Coupe'
slug: volkswagen-w12-coupe
blueprint:
    star1: Key
    star2: 26
    star3: 34
    star4: 46
    star5: 61
    star6: 78
    total: 245
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 9
    handling: 1
    nitro: 3
    mark: 3
    division: 9
rank:
    star0: 2337
    star1: 2576
    star2: 2853
    star3: 3145
    star4: 3532
    star5: 4005
    star6: 4348
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 370.5
    acceleration: 79.08
    handling: 84.44
    nitro: 54.64
    average: 147.17
statMin:
    speed: 357.0
    acceleration: 68.5
    handling: 57.23
    nitro: 30.21
    average: 128.24
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 32
    rare: 20
    epic: 12
settingBlueprint:
    star1: Key
    star2: 26
    star3: 34
    star4: 46
    star5: 61
    star6: 78
    total: 245
settingBrand:
    name: Volkswagen
settingClass:
    value: B
    carsNumber: 72
    median: 146
settingLevel:
    level: 13
    common: 32
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 9890
    level02: 16100
    level03: 25800
    level04: 38700
    level05: 55900
    level06: 78500
    level07: 109500
    level08: 153500
    level09: 214500
    level10: 300500
    level11: 421000
    level12: 589000
    level13: 967500
    common: 70000
    rare: 140000
    epic: 420000
