id: 49
stars: 5
gameUpdate: 0
carOrder: 5
statOrder: 68
level: 12
epic: 12
model: 'Lykan Hypersport'
slug: w-motors-lykan-hypersport
blueprint:
    star1: '40'
    star2: 13
    star3: 16
    star4: 25
    star5: 39
    star6: 0
    total: 133
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 3
    mark: 2
    division: 9
rank:
    star0: 3013
    star1: 3168
    star2: 3346
    star3: 3524
    star4: 3800
    star5: 4083
    star6: 0
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 407.5
    acceleration: 80.48
    handling: 40.97
    nitro: 58.26
    average: 146.8
statMin:
    speed: 395.0
    acceleration: 74.8
    handling: 37.0
    nitro: 39.79
    average: 136.65
upgrade:
    speed: 12
    acceleration: 12
    handling: 12
    nitro: 12
    common: 28
    rare: 20
    epic: 12
settingBlueprint:
    star1: '40'
    star2: 13
    star3: 16
    star4: 25
    star5: 39
    star6: 0
    total: 133
settingBrand:
    name: 'W Motors'
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 12
    common: 28
    rare: 20
    epic: 12
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
