id: 313
stars: 6
gameUpdate: 46
carOrder: 63
statOrder: 99
level: 6
epic: 0
model: 'Aurora Agil'
slug: zenvo-aurora-agil
blueprint:
    star1: '30'
    star2: 35
    star3: 4
    star4: 0
    star5: 0
    star6: 0
    total: 69
evo:
    number: 0
gauntlet:
    speed: 2
    acceleration: 2
    handling: 2
    nitro: 2
    mark: 2
    division: 9
rank:
    star0: 3243
    star1: 3418
    star2: 0
    star3: 0
    star4: 0
    star5: 0
    star6: 4531
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 379.5
    acceleration: 83.12
    handling: 70.29
    nitro: 64.25
    average: 149.29
statMin:
    speed: 365.0
    acceleration: 77.5
    handling: 50.67
    nitro: 41.74
    average: 133.73
upgrade:
    speed: 6
    acceleration: 6
    handling: 6
    nitro: 6
    common: 16
    rare: 4
    epic: 0
settingBlueprint:
    star1: '30'
    star2: 35
    star3: 40
    star4: 45
    star5: 55
    star6: 65
    total: 270
settingBrand:
    name: Zenvo
settingClass:
    value: A
    carsNumber: 64
    median: 150
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 16100
    level02: 26300
    level03: 42000
    level04: 63000
    level05: 91000
    level06: 127500
    level07: 178500
    level08: 249500
    level09: 349500
    level10: 489500
    level11: 685000
    level12: 959000
    level13: 1575000
    common: 80000
    rare: 160000
    epic: 480000
