id: 244
stars: 6
gameUpdate: 36
carOrder: 65
statOrder: 15
level: 13
epic: 3
model: 'Aurora Tur'
slug: zenvo-aurora-tur
blueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
evo:
    number: 0
gauntlet:
    speed: 1
    acceleration: 3
    handling: 3
    nitro: 9
    mark: 4
    division: 9
rank:
    star0: 3869
    star1: 4028
    star2: 4216
    star3: 4418
    star4: 4626
    star5: 4871
    star6: 5100
statActual:
    speed: 0.0
    acceleration: 0.0
    handling: 0.0
    nitro: 0.0
    average: 0.0
statMax:
    speed: 467.5
    acceleration: 81.73
    handling: 56.53
    nitro: 42.65
    average: 162.1
statMin:
    speed: 450.0
    acceleration: 79.3
    handling: 52.05
    nitro: 27.52
    average: 152.22
upgrade:
    speed: 13
    acceleration: 13
    handling: 13
    nitro: 13
    common: 28
    rare: 20
    epic: 1
settingBlueprint:
    star1: '85'
    star2: 25
    star3: 29
    star4: 38
    star5: 54
    star6: 69
    total: 300
settingBrand:
    name: Zenvo
settingClass:
    value: S
    carsNumber: 78
    median: 159
settingLevel:
    level: 13
    common: 28
    rare: 20
    epic: 16
settingUnitPrice:
    level01: 23000
    level02: 37500
    level03: 60000
    level04: 90000
    level05: 130000
    level06: 182000
    level07: 255000
    level08: 356500
    level09: 499500
    level10: 699000
    level11: 979000
    level12: 1370000
    level13: 2250000
    common: 90000
    rare: 180000
    epic: 540000
