parameters:
    ### FILES
    csv.file.garage.app:                    'app.csv'
    csv.file.garage.blueprint:              'garage-blueprint.csv'
    csv.file.garage.gauntlet:               'garage-gauntlet.csv'
    csv.file.garage.rank:                   'garage-rank.csv'
    csv.file.garage.setting.blueprint:      'setting-blueprint.csv'
    csv.file.garage.setting.level:          'setting-level.csv'
    csv.file.garage.setting.unit-price:     'setting-price.csv'
#    csv.file.garage.setting.class:          'setting-class.csv'
#    csv.file.garage.setting.tag:            'setting-tag.csv'
    csv.file.garage.stat-actual:            'garage-stat-actual.csv'
    csv.file.garage.stat-max:               'garage-stat-max.csv'
    csv.file.garage.stat-min:               'garage-stat-min.csv'
    csv.file.garage.status-control:         'garage-status-control.csv'
    csv.file.garage.status:                 'garage-status.csv'
    csv.file.garage.upgrade:                'garage-upgrade.csv'
    csv.file.inventory.app:                 'app.csv'
    csv.file.mission.app:                   'app.csv'
    csv.file.mission.task:                  'task.csv'
    csv.file.mission.type:                  'type.csv'
    csv.file.race.app:                      'app.csv'
    csv.file.race.mode:                     'mode.csv'
    csv.file.race.region:                   'region.csv'
    csv.file.race.season:                   'season.csv'
    csv.file.race.time:                     'time.csv'
    csv.file.race.track:                    'track.csv'
    csv.file.setting.blueprint:             'blueprint.csv'
    csv.file.setting.brand:                 'brand.csv'
    csv.file.setting.class:                 'class.csv'
    csv.file.setting.level:                 'level.csv'
    csv.file.setting.tag:                   'tag.csv'
    csv.file.setting.unit-price:            'unit-price.csv'

    csv.file.order.class:                   'class-%s.csv'
