# https://taskfile.dev

version: '3'

includes:
    A9: ../taskfile/Asphalt.yaml
    Com: ../taskfile/Composer.yaml
    Test: ../taskfile/PHPUnit.yaml
    Sym: ../taskfile/Symfony.yaml

vars:
    GREETING: Hello, World!

env:
    dev: --env dev

tasks:
    default:
        desc: Print a greeting message
        cmds:
            - echo "{{.GREETING}}"
        silent: true

    greet:
        cmds:
            - echo $dev
