### Garage
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `garage_app`.`stars` AS `Stars`, `garage_app`.`game_update` AS `GameUpdate`, `garage_app`.`car_order` AS `CarOrder`, `garage_app`.`stat_order` AS `StatOrder`, `garage_app`.`level` AS `Level`, `garage_app`.`epic` AS `Epic`, `setting_class`.`value` AS `SettingClassValue` FROM `garage_app` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` INNER JOIN `setting_class` ON `setting_class`.`id` = `garage_app`.`setting_class_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\garages\app.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `garage_status`.`full_upgrade_speed` AS `FullSpeed`, `garage_status`.`full_upgrade_acceleration` AS `FullAcceleration`, `garage_status`.`full_upgrade_handling` AS `FullHandling`, `garage_status`.`full_upgrade_nitro` AS `FullNitro`, `garage_status`.`full_upgrade_level` AS `FullUpgrade`, `garage_status`.`full_upgrade_common` AS `FullCommon`, `garage_status`.`full_upgrade_rare` AS `FullRare`, `garage_status`.`full_upgrade_epic` AS `FullEpic`, `garage_status`.`full_blueprint_star1` AS `FullStar1`, `garage_status`.`full_blueprint_star2` AS `FullStar2`, `garage_status`.`full_blueprint_star3` AS `FullStar3`, `garage_status`.`full_blueprint_star4` AS `FullStar4`, `garage_status`.`full_blueprint_star5` AS `FullStar5`, `garage_status`.`full_blueprint_star6` AS `FullStar6`, `garage_status`.`to_install_upgrade_speed` AS `ToInstallSpeed`, `garage_status`.`to_install_upgrade_acceleration` AS `ToInstallAcceleration`, `garage_status`.`to_install_upgrade_handling` AS `ToInstallHandling`, `garage_status`.`to_install_upgrade_nitro` AS `ToInstallNitro`, `garage_status`.`to_install_upgrade_common` AS `ToInstallUpgrade`, `garage_status`.`to_install_upgrade_rare` AS `ToInstallCommon`, `garage_status`.`to_install_upgrade_epic` AS `ToInstallRare`, `garage_status`.`to_unblock` AS `ToUnblock`, `garage_status`.`to_gold` AS `ToGold` FROM `garage_status` INNER JOIN `garage_app` ON `garage_status`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC ;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-status-control.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `garage_status`.`unblock` AS `Unblock`, `garage_status`.`gold` AS `Gold`, `garage_status`.`to_upgrade_level` AS `ToUpgrade` FROM `garage_status` INNER JOIN `garage_app` ON `garage_status`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC ;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-status.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `garage_upgrade`.`speed` AS `Speed`, `garage_upgrade`.`acceleration` AS `Acceleration`, `garage_upgrade`.`handling` AS `Handling`, `garage_upgrade`.`nitro` AS `Nitro`, `garage_upgrade`.`common` AS `Common`, `garage_upgrade`.`rare` AS `Rare`, `garage_upgrade`.`epic` AS `Epic` FROM `garage_upgrade` INNER JOIN `garage_app` ON `garage_upgrade`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC ;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-upgrade.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `setting_blueprint`.`slug` AS `SettingBlueprint` FROM `garage_app` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` INNER JOIN `setting_blueprint` ON `setting_blueprint`.`id` = `garage_app`.`setting_blueprint_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\garages\setting-blueprint.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `setting_level`.`slug` AS `SettingLevel` FROM `garage_app` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` INNER JOIN `setting_level` ON `setting_level`.`id` = `garage_app`.`setting_level_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\garages\setting-level.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `setting_unit_price`.`slug` AS `SettingPrice` FROM `garage_app` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` INNER JOIN `setting_unit_price` ON `setting_unit_price`.`id` = `garage_app`.`setting_unit_price_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\garages\setting-price.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `speed` AS `Speed`, `acceleration` AS `Acceleration`, `handling` AS `Handling`, `nitro` AS `Nitro`, `average` AS `Average` FROM `garage_stat_actual` INNER JOIN `garage_app` ON `garage_stat_actual`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC ;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-stat-actual.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `speed` AS `Speed`, `acceleration` AS `Acceleration`, `handling` AS `Handling`, `nitro` AS `Nitro`, `average` AS `Average` FROM `garage_stat_max` INNER JOIN `garage_app` ON `garage_stat_max`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC ;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-stat-max.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `speed` AS `Speed`, `acceleration` AS `Acceleration`, `handling` AS `Handling`, `nitro` AS `Nitro`, `average` AS `Average` FROM `garage_stat_min` INNER JOIN `garage_app` ON `garage_stat_min`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC ;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-stat-min.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `speed` AS `Speed`, `acceleration` AS `Acceleration`, `handling` AS `Handling`, `nitro` AS `Nitro`, `division` AS `Division` FROM `garage_gauntlet` INNER JOIN `garage_app` ON `garage_gauntlet`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-gauntlet.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `star0` AS `Star0`, `star1` AS `Star1`, `star2` AS `Star2`, `star3` AS `Star3`, `star4` AS `Star4`, `star5` AS `Star5`, `star6` AS `Star6` FROM `garage_rank` INNER JOIN `garage_app` ON `garage_rank`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-rank.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `setting_brand`.`name` AS `Brand`, `garage_app`.`model` AS `Model`, `star1` AS `Star1`, `star2` AS `Star2`, `star3` AS `Star3`, `star4` AS `Star4`, `star5` AS `Star5`, `star6` AS `Star6` FROM `garage_blueprint` INNER JOIN `garage_app` ON `garage_blueprint`.`garage_id` = `garage_app`.`id` INNER JOIN `setting_brand` ON `setting_brand`.`id` = `garage_app`.`setting_brand_id` ORDER BY `setting_brand`.`name` ASC, `garage_app`.`model` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\garages\garage-blueprint.csv
### Inventory
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `category` AS Category, `label` AS `Label`, `value` AS `Value`, `filter` AS `Filter`, `position` AS `Position`, `active` AS `Active` FROM `inventory_app`;" > E:\Symfony\Asphalt\documents\csv\migration\inventory.csv
### Mission
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `value` AS `Value`, `slug` AS `Slug` FROM `mission_task`;" > E:\Symfony\Asphalt\documents\csv\migration\missions\task.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `value` AS `Value`, `slug` AS `Slug` FROM `mission_type`;" > E:\Symfony\Asphalt\documents\csv\migration\missions\type.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `week` AS 'Week',   `region` AS 'Region',   `track` AS 'Track',   `class` AS 'Class',   `brand` AS 'Brand',   `description` AS 'Description',   `success` AS 'Success',   `target` AS 'Target',  `mission_task`.`value` AS `Task`, `mission_type`.`value` AS `Type` FROM `mission_app` INNER JOIN `mission_task` ON `mission_app`.`task_id` = `mission_task`.`id` INNER JOIN `mission_type` ON `mission_app`.`type_id` = `mission_type`.`id` ORDER BY `week` ASC ;" > E:\Symfony\Asphalt\documents\csv\migration\missions\app.csv
### Race
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `chapter` AS `Chapter`, `name` AS `Name` FROM `race_season` ORDER BY `Chapter` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\races\season.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `name_english` AS `English`, `name_french` AS `French`, `race_region`.`name` AS `Region` FROM `race_track` INNER JOIN `race_region` ON `race_track`.`region_id` = `race_region`.`id` ORDER BY `Region` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\races\track.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `name` AS `Name` FROM `race_mode` ORDER BY `Name` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\races\mode.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `name` AS `Name` FROM `race_time` ORDER BY `Name` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\races\time.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `name` AS `Name` FROM`race_region` ORDER BY `Name` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\races\region.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `race_season`.`name` AS `Season`, `race_order` AS `RaceOrder`, `race_mode`.`name` AS `Mode`, `race_time`.`name` AS `Time`, `race_track`. `name_english` AS `English`, `finished` AS `Finished` FROM `race_app` INNER JOIN `race_mode` ON `race_app`.`mode_id` = `race_mode`.`id` INNER JOIN `race_season` ON `race_app`.`season_id` = `race_season`.`id` INNER JOIN `race_time` ON `race_app`.`time_id` = `race_time`.`id` INNER JOIN `race_track` ON `race_app`.`track_id` = `race_track`.`id` ORDER BY `race_season`.`chapter` ASC, `race_season`.`name` ASC, `RaceOrder` ASC ;" > E:\Symfony\Asphalt\documents\csv\migration\races\app.csv
### Setting
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `label` AS `Label`, `value` AS `Value`, `class_order` AS `Order`, `cars_number` AS `Number`, `median` AS `Median` FROM `setting_class` ORDER BY `Label` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\settings\class.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `level01` AS `Level01`, `level02` AS `Level02`, `level03` AS `Level03`, `level04` AS `Level04`, `level05` AS `Level05`, `level06` AS `Level06`, `level07` AS `Level07`, `level08` AS `Level08`, `level09` AS `Level09`, `level10`  AS` Level10`, `level11` AS `Level11`, `level12` AS `Level12`, `level13` AS `Level13`, `common` AS `Common`, `rare` AS `Rare`, `epic` AS `Epic` FROM `setting_unit_price`;" > E:\Symfony\Asphalt\documents\csv\migration\settings\unit-price.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `level` AS `Level`, `common` AS `Common`, `rare` AS `Rare`, `epic` AS `Epic` FROM `setting_level`;" > E:\Symfony\Asphalt\documents\csv\migration\settings\level.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `name` AS `Name`, `cars_number` AS `Number` FROM `setting_brand` ORDER BY `Name` ASC;" > E:\Symfony\Asphalt\documents\csv\migration\settings\brand.csv
mysql -u root -p sym-asphalt-v7 --batch --raw -e "SELECT `star1` AS `Star1`, `star2` AS `Star2`, `star3` AS `Star3`, `star4` AS `Star4`, `star5` AS `Star5`, `star6` AS `Star6` FROM `setting_blueprint` ORDER BY `Star1`;" > E:\Symfony\Asphalt\documents\csv\migration\settings\blueprint.csv
