parameters:
    metas:
        title:              'Asphalt Legends Unite'
        author:             'Giancarlo PALUMBO'
        email:              'giancarlo.palumbo@free.fr'
        description:        ~
        generator:          ~
    classes:
        index_table:        'table table-bordered table-striped'
        index_btn:          'btn btn-outline-info border border-info rounded-right rounded-4 py-0'
        input:              'form-control form-control-sm bg-transparent text-center fw-bolder'
    images:
        logo:               'images/logo-white.png'
    games:
        pack:               6
        pack_price:         900
    cache_lifetime:
        inventories:         300 # 3600    # (60 * 60 = 1 hour)
        statistical:         300 # 3600    # (60 * 60 = 1 hour)
        garages:             300 # 3600    # (60 * 60 = 1 hour)
        races:               300 # 2678400 # (60 * 60 * 24 * 31 = 1 month)
