# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    providers:
        doctrine:
            # table_prefix: null
            table_prefix: 'audit-log-'
            # table_suffix: '_audit'
            table_suffix: ~
            # columns ignored from auditing
            ignored_columns:
                - 'createdAt'
                - 'updatedAt'
            viewer: true

    timezone: 'Europe/Paris'
